// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol/v1beta1/accesscontrol.proto

package accesscontrol

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AccessOperation struct {
	AccessType         AccessType   `protobuf:"varint,1,opt,name=access_type,json=accessType,proto3,enum=cosmos.accesscontrol.v1beta1.AccessType" json:"access_type,omitempty"`
	ResourceType       ResourceType `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cosmos.accesscontrol.v1beta1.ResourceType" json:"resource_type,omitempty"`
	IdentifierTemplate string       `protobuf:"bytes,3,opt,name=identifier_template,json=identifierTemplate,proto3" json:"identifier_template,omitempty"`
}

func (m *AccessOperation) Reset()         { *m = AccessOperation{} }
func (m *AccessOperation) String() string { return proto.CompactTextString(m) }
func (*AccessOperation) ProtoMessage()    {}
func (*AccessOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{0}
}
func (m *AccessOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccessOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccessOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccessOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessOperation.Merge(m, src)
}
func (m *AccessOperation) XXX_Size() int {
	return m.Size()
}
func (m *AccessOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessOperation.DiscardUnknown(m)
}

var xxx_messageInfo_AccessOperation proto.InternalMessageInfo

func (m *AccessOperation) GetAccessType() AccessType {
	if m != nil {
		return m.AccessType
	}
	return AccessType_UNKNOWN
}

func (m *AccessOperation) GetResourceType() ResourceType {
	if m != nil {
		return m.ResourceType
	}
	return ResourceType_ANY
}

func (m *AccessOperation) GetIdentifierTemplate() string {
	if m != nil {
		return m.IdentifierTemplate
	}
	return ""
}

type WasmAccessOperation struct {
	Operation    *AccessOperation            `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	SelectorType AccessOperationSelectorType `protobuf:"varint,2,opt,name=selector_type,json=selectorType,proto3,enum=cosmos.accesscontrol.v1beta1.AccessOperationSelectorType" json:"selector_type,omitempty"`
	Selector     string                      `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (m *WasmAccessOperation) Reset()         { *m = WasmAccessOperation{} }
func (m *WasmAccessOperation) String() string { return proto.CompactTextString(m) }
func (*WasmAccessOperation) ProtoMessage()    {}
func (*WasmAccessOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{1}
}
func (m *WasmAccessOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmAccessOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmAccessOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmAccessOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmAccessOperation.Merge(m, src)
}
func (m *WasmAccessOperation) XXX_Size() int {
	return m.Size()
}
func (m *WasmAccessOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmAccessOperation.DiscardUnknown(m)
}

var xxx_messageInfo_WasmAccessOperation proto.InternalMessageInfo

func (m *WasmAccessOperation) GetOperation() *AccessOperation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *WasmAccessOperation) GetSelectorType() AccessOperationSelectorType {
	if m != nil {
		return m.SelectorType
	}
	return AccessOperationSelectorType_NONE
}

func (m *WasmAccessOperation) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

type WasmContractReference struct {
	ContractAddress         string             `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	MessageType             WasmMessageSubtype `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=cosmos.accesscontrol.v1beta1.WasmMessageSubtype" json:"message_type,omitempty"`
	MessageName             string             `protobuf:"bytes,3,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	JsonTranslationTemplate string             `protobuf:"bytes,4,opt,name=json_translation_template,json=jsonTranslationTemplate,proto3" json:"json_translation_template,omitempty"`
}

func (m *WasmContractReference) Reset()         { *m = WasmContractReference{} }
func (m *WasmContractReference) String() string { return proto.CompactTextString(m) }
func (*WasmContractReference) ProtoMessage()    {}
func (*WasmContractReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{2}
}
func (m *WasmContractReference) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmContractReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmContractReference.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmContractReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmContractReference.Merge(m, src)
}
func (m *WasmContractReference) XXX_Size() int {
	return m.Size()
}
func (m *WasmContractReference) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmContractReference.DiscardUnknown(m)
}

var xxx_messageInfo_WasmContractReference proto.InternalMessageInfo

func (m *WasmContractReference) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *WasmContractReference) GetMessageType() WasmMessageSubtype {
	if m != nil {
		return m.MessageType
	}
	return WasmMessageSubtype_QUERY
}

func (m *WasmContractReference) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *WasmContractReference) GetJsonTranslationTemplate() string {
	if m != nil {
		return m.JsonTranslationTemplate
	}
	return ""
}

type WasmContractReferences struct {
	MessageName        string                   `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	ContractReferences []*WasmContractReference `protobuf:"bytes,2,rep,name=contract_references,json=contractReferences,proto3" json:"contract_references,omitempty"`
}

func (m *WasmContractReferences) Reset()         { *m = WasmContractReferences{} }
func (m *WasmContractReferences) String() string { return proto.CompactTextString(m) }
func (*WasmContractReferences) ProtoMessage()    {}
func (*WasmContractReferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{3}
}
func (m *WasmContractReferences) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmContractReferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmContractReferences.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmContractReferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmContractReferences.Merge(m, src)
}
func (m *WasmContractReferences) XXX_Size() int {
	return m.Size()
}
func (m *WasmContractReferences) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmContractReferences.DiscardUnknown(m)
}

var xxx_messageInfo_WasmContractReferences proto.InternalMessageInfo

func (m *WasmContractReferences) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *WasmContractReferences) GetContractReferences() []*WasmContractReference {
	if m != nil {
		return m.ContractReferences
	}
	return nil
}

type WasmAccessOperations struct {
	MessageName    string                 `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	WasmOperations []*WasmAccessOperation `protobuf:"bytes,2,rep,name=wasm_operations,json=wasmOperations,proto3" json:"wasm_operations,omitempty"`
}

func (m *WasmAccessOperations) Reset()         { *m = WasmAccessOperations{} }
func (m *WasmAccessOperations) String() string { return proto.CompactTextString(m) }
func (*WasmAccessOperations) ProtoMessage()    {}
func (*WasmAccessOperations) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{4}
}
func (m *WasmAccessOperations) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmAccessOperations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmAccessOperations.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmAccessOperations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmAccessOperations.Merge(m, src)
}
func (m *WasmAccessOperations) XXX_Size() int {
	return m.Size()
}
func (m *WasmAccessOperations) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmAccessOperations.DiscardUnknown(m)
}

var xxx_messageInfo_WasmAccessOperations proto.InternalMessageInfo

func (m *WasmAccessOperations) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *WasmAccessOperations) GetWasmOperations() []*WasmAccessOperation {
	if m != nil {
		return m.WasmOperations
	}
	return nil
}

type MessageDependencyMapping struct {
	MessageKey     string            `protobuf:"bytes,1,opt,name=message_key,json=messageKey,proto3" json:"message_key,omitempty"`
	AccessOps      []AccessOperation `protobuf:"bytes,2,rep,name=access_ops,json=accessOps,proto3" json:"access_ops"`
	DynamicEnabled bool              `protobuf:"varint,3,opt,name=dynamic_enabled,json=dynamicEnabled,proto3" json:"dynamic_enabled,omitempty"`
}

func (m *MessageDependencyMapping) Reset()         { *m = MessageDependencyMapping{} }
func (m *MessageDependencyMapping) String() string { return proto.CompactTextString(m) }
func (*MessageDependencyMapping) ProtoMessage()    {}
func (*MessageDependencyMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{5}
}
func (m *MessageDependencyMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageDependencyMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessageDependencyMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MessageDependencyMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageDependencyMapping.Merge(m, src)
}
func (m *MessageDependencyMapping) XXX_Size() int {
	return m.Size()
}
func (m *MessageDependencyMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageDependencyMapping.DiscardUnknown(m)
}

var xxx_messageInfo_MessageDependencyMapping proto.InternalMessageInfo

func (m *MessageDependencyMapping) GetMessageKey() string {
	if m != nil {
		return m.MessageKey
	}
	return ""
}

func (m *MessageDependencyMapping) GetAccessOps() []AccessOperation {
	if m != nil {
		return m.AccessOps
	}
	return nil
}

func (m *MessageDependencyMapping) GetDynamicEnabled() bool {
	if m != nil {
		return m.DynamicEnabled
	}
	return false
}

type WasmDependencyMapping struct {
	BaseAccessOps             []*WasmAccessOperation    `protobuf:"bytes,1,rep,name=base_access_ops,json=baseAccessOps,proto3" json:"base_access_ops,omitempty"`
	QueryAccessOps            []*WasmAccessOperations   `protobuf:"bytes,2,rep,name=query_access_ops,json=queryAccessOps,proto3" json:"query_access_ops,omitempty"`
	ExecuteAccessOps          []*WasmAccessOperations   `protobuf:"bytes,3,rep,name=execute_access_ops,json=executeAccessOps,proto3" json:"execute_access_ops,omitempty"`
	BaseContractReferences    []*WasmContractReference  `protobuf:"bytes,4,rep,name=base_contract_references,json=baseContractReferences,proto3" json:"base_contract_references,omitempty"`
	QueryContractReferences   []*WasmContractReferences `protobuf:"bytes,5,rep,name=query_contract_references,json=queryContractReferences,proto3" json:"query_contract_references,omitempty"`
	ExecuteContractReferences []*WasmContractReferences `protobuf:"bytes,6,rep,name=execute_contract_references,json=executeContractReferences,proto3" json:"execute_contract_references,omitempty"`
	ResetReason               string                    `protobuf:"bytes,7,opt,name=reset_reason,json=resetReason,proto3" json:"reset_reason,omitempty"`
	ContractAddress           string                    `protobuf:"bytes,8,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *WasmDependencyMapping) Reset()         { *m = WasmDependencyMapping{} }
func (m *WasmDependencyMapping) String() string { return proto.CompactTextString(m) }
func (*WasmDependencyMapping) ProtoMessage()    {}
func (*WasmDependencyMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_5314e18d3eee2037, []int{6}
}
func (m *WasmDependencyMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmDependencyMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmDependencyMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmDependencyMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmDependencyMapping.Merge(m, src)
}
func (m *WasmDependencyMapping) XXX_Size() int {
	return m.Size()
}
func (m *WasmDependencyMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmDependencyMapping.DiscardUnknown(m)
}

var xxx_messageInfo_WasmDependencyMapping proto.InternalMessageInfo

func (m *WasmDependencyMapping) GetBaseAccessOps() []*WasmAccessOperation {
	if m != nil {
		return m.BaseAccessOps
	}
	return nil
}

func (m *WasmDependencyMapping) GetQueryAccessOps() []*WasmAccessOperations {
	if m != nil {
		return m.QueryAccessOps
	}
	return nil
}

func (m *WasmDependencyMapping) GetExecuteAccessOps() []*WasmAccessOperations {
	if m != nil {
		return m.ExecuteAccessOps
	}
	return nil
}

func (m *WasmDependencyMapping) GetBaseContractReferences() []*WasmContractReference {
	if m != nil {
		return m.BaseContractReferences
	}
	return nil
}

func (m *WasmDependencyMapping) GetQueryContractReferences() []*WasmContractReferences {
	if m != nil {
		return m.QueryContractReferences
	}
	return nil
}

func (m *WasmDependencyMapping) GetExecuteContractReferences() []*WasmContractReferences {
	if m != nil {
		return m.ExecuteContractReferences
	}
	return nil
}

func (m *WasmDependencyMapping) GetResetReason() string {
	if m != nil {
		return m.ResetReason
	}
	return ""
}

func (m *WasmDependencyMapping) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessOperation)(nil), "cosmos.accesscontrol.v1beta1.AccessOperation")
	proto.RegisterType((*WasmAccessOperation)(nil), "cosmos.accesscontrol.v1beta1.WasmAccessOperation")
	proto.RegisterType((*WasmContractReference)(nil), "cosmos.accesscontrol.v1beta1.WasmContractReference")
	proto.RegisterType((*WasmContractReferences)(nil), "cosmos.accesscontrol.v1beta1.WasmContractReferences")
	proto.RegisterType((*WasmAccessOperations)(nil), "cosmos.accesscontrol.v1beta1.WasmAccessOperations")
	proto.RegisterType((*MessageDependencyMapping)(nil), "cosmos.accesscontrol.v1beta1.MessageDependencyMapping")
	proto.RegisterType((*WasmDependencyMapping)(nil), "cosmos.accesscontrol.v1beta1.WasmDependencyMapping")
}

func init() {
	proto.RegisterFile("cosmos/accesscontrol/v1beta1/accesscontrol.proto", fileDescriptor_5314e18d3eee2037)
}

var fileDescriptor_5314e18d3eee2037 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x52, 0x13, 0x4b,
	0x14, 0xce, 0xf0, 0x77, 0x49, 0x07, 0x12, 0xaa, 0xe1, 0x42, 0xe0, 0xde, 0x0a, 0xdc, 0x6c, 0x6e,
	0xb4, 0x24, 0x81, 0xe0, 0x46, 0x77, 0xa0, 0x2e, 0x94, 0x42, 0xaa, 0x06, 0xaa, 0x2c, 0x29, 0xcb,
	0xb1, 0xd3, 0x73, 0x88, 0x91, 0x4c, 0xf7, 0x38, 0xdd, 0x51, 0xf3, 0x16, 0x6e, 0x7c, 0x00, 0xdf,
	0xc2, 0x47, 0x60, 0xc9, 0x4e, 0x57, 0x94, 0x05, 0xef, 0xe0, 0xda, 0x9a, 0xee, 0x9e, 0x99, 0x84,
	0x4c, 0x05, 0x88, 0xab, 0xa4, 0x4f, 0x9f, 0xf3, 0xfd, 0x9c, 0x3e, 0xdd, 0x83, 0x36, 0x28, 0x17,
	0x1e, 0x17, 0x35, 0x42, 0x29, 0x08, 0x41, 0x39, 0x93, 0x01, 0x6f, 0xd7, 0x3e, 0x6c, 0x36, 0x40,
	0x92, 0xcd, 0xfe, 0x68, 0xd5, 0x0f, 0xb8, 0xe4, 0xf8, 0x5f, 0x5d, 0x51, 0xed, 0xdf, 0x33, 0x15,
	0x2b, 0x0b, 0x4d, 0xde, 0xe4, 0x2a, 0xb1, 0x16, 0xfe, 0xd3, 0x35, 0x2b, 0xf7, 0x86, 0xb2, 0x50,
	0xce, 0x84, 0x24, 0x4c, 0x0a, 0x9d, 0x5d, 0x3e, 0xb7, 0x50, 0x61, 0x5b, 0x65, 0xee, 0xfb, 0x10,
	0x10, 0xd9, 0xe2, 0x0c, 0x3f, 0x45, 0x39, 0x5d, 0xec, 0xc8, 0xae, 0x0f, 0x45, 0x6b, 0xcd, 0xaa,
	0xe4, 0xeb, 0x95, 0xea, 0x30, 0x2d, 0x55, 0x8d, 0x71, 0xd8, 0xf5, 0xc1, 0x46, 0x24, 0xfe, 0x8f,
	0xf7, 0xd1, 0x6c, 0x00, 0x82, 0x77, 0x02, 0x0a, 0x1a, 0x6c, 0x4c, 0x81, 0xdd, 0x1d, 0x0e, 0x66,
	0x9b, 0x12, 0x05, 0x37, 0x13, 0xf4, 0xac, 0x70, 0x0d, 0xcd, 0xb7, 0x5c, 0x60, 0xb2, 0x75, 0xdc,
	0x82, 0xc0, 0x91, 0xe0, 0xf9, 0x6d, 0x22, 0xa1, 0x38, 0xbe, 0x66, 0x55, 0xb2, 0x36, 0x4e, 0xb6,
	0x0e, 0xcd, 0x4e, 0x68, 0x70, 0xfe, 0x05, 0x11, 0xde, 0x55, 0x93, 0xbb, 0x28, 0xcb, 0xa3, 0x85,
	0xb2, 0x98, 0xab, 0xaf, 0xdf, 0xc4, 0x62, 0x8c, 0x60, 0x27, 0xf5, 0xf8, 0x35, 0x9a, 0x15, 0xd0,
	0x06, 0x2a, 0x79, 0xd0, 0x6b, 0xf3, 0xc1, 0xad, 0x00, 0x0f, 0x0c, 0x82, 0x76, 0x2d, 0x7a, 0x56,
	0x78, 0x05, 0x4d, 0x47, 0x6b, 0x63, 0x35, 0x5e, 0x97, 0x7f, 0x59, 0xe8, 0xef, 0xd0, 0xe0, 0xa3,
	0x10, 0x9d, 0x50, 0x69, 0xc3, 0x31, 0x04, 0xc0, 0x28, 0xe0, 0x3b, 0x68, 0x8e, 0x9a, 0xa0, 0x43,
	0x5c, 0x37, 0x00, 0x21, 0x94, 0xd3, 0xac, 0x5d, 0x88, 0xe2, 0xdb, 0x3a, 0x8c, 0x0f, 0xd0, 0x8c,
	0x07, 0x42, 0x90, 0x66, 0xdf, 0x31, 0x6d, 0x0c, 0xd7, 0x1f, 0xb2, 0xee, 0xe9, 0xaa, 0x83, 0x4e,
	0x23, 0xac, 0xb3, 0x73, 0x06, 0x45, 0xa9, 0xfe, 0x2f, 0x01, 0x65, 0xc4, 0x8b, 0x0e, 0x29, 0x4a,
	0x79, 0x4e, 0x3c, 0xc0, 0x0f, 0xd1, 0xf2, 0x3b, 0xc1, 0x99, 0x23, 0x03, 0xc2, 0x44, 0x5b, 0xb5,
	0x21, 0x39, 0xd4, 0x09, 0x95, 0xbf, 0x14, 0x26, 0x1c, 0x26, 0xfb, 0xf1, 0xc9, 0x7e, 0xb5, 0xd0,
	0x62, 0xaa, 0x71, 0x31, 0xc0, 0x6c, 0x0d, 0x32, 0xbb, 0x68, 0x3e, 0x6e, 0x4e, 0x10, 0x57, 0x16,
	0xc7, 0xd6, 0xc6, 0x2b, 0xb9, 0xfa, 0xd6, 0xf5, 0xc6, 0x07, 0x58, 0x6d, 0x4c, 0x07, 0x84, 0x94,
	0xbf, 0x58, 0x68, 0x21, 0x65, 0xfa, 0x6e, 0xa4, 0xf0, 0x08, 0x15, 0x3e, 0x12, 0xe1, 0x39, 0xf1,
	0x98, 0x45, 0xea, 0x36, 0xaf, 0x57, 0x77, 0x75, 0x56, 0xf3, 0x21, 0x52, 0x42, 0x5f, 0xfe, 0x66,
	0xa1, 0xa2, 0x39, 0xba, 0xc7, 0xe0, 0x03, 0x73, 0x81, 0xd1, 0xee, 0x1e, 0xf1, 0xfd, 0x16, 0x6b,
	0xe2, 0x55, 0x14, 0xe9, 0x70, 0x4e, 0xa0, 0x6b, 0xa4, 0x21, 0x13, 0xda, 0x85, 0x2e, 0xb6, 0x91,
	0xb9, 0xe3, 0x0e, 0xf7, 0x23, 0x51, 0xb7, 0xbb, 0x3c, 0x3b, 0x13, 0xa7, 0xe7, 0xab, 0x19, 0x3b,
	0x4b, 0x4c, 0x58, 0xe0, 0xff, 0x51, 0xc1, 0xed, 0x32, 0xe2, 0xb5, 0xa8, 0x03, 0x8c, 0x34, 0xda,
	0xe0, 0xaa, 0x79, 0x99, 0xb6, 0xf3, 0x26, 0xfc, 0x44, 0x47, 0xcb, 0xdf, 0x27, 0xf5, 0xbc, 0x0f,
	0xea, 0x7e, 0x89, 0x0a, 0x0d, 0x22, 0xc0, 0xe9, 0xd1, 0x66, 0x8d, 0xda, 0xb0, 0xd9, 0x10, 0x69,
	0x3b, 0x56, 0xf7, 0x0a, 0xcd, 0xbd, 0xef, 0x40, 0xd0, 0x75, 0x06, 0x7c, 0xd7, 0x6f, 0x8d, 0x2d,
	0xec, 0xbc, 0xc2, 0x4a, 0xd0, 0xdf, 0x20, 0x0c, 0x9f, 0x80, 0x76, 0x64, 0x9f, 0xf6, 0xf1, 0x91,
	0xf1, 0xe7, 0x0c, 0x5a, 0xc2, 0xe0, 0xa1, 0xa2, 0x6a, 0x4d, 0xda, 0xc8, 0x4f, 0x8c, 0x3e, 0xf2,
	0x8b, 0x21, 0x68, 0xca, 0xfd, 0xf3, 0xd1, 0xb2, 0x6e, 0x57, 0x1a, 0xdf, 0xa4, 0xe2, 0xbb, 0x3f,
	0x02, 0x9f, 0xb0, 0x97, 0x14, 0x6c, 0x0a, 0xa3, 0x44, 0xff, 0x44, 0x2d, 0x4c, 0xe3, 0x9c, 0xfa,
	0x03, 0xce, 0x65, 0x03, 0x9c, 0xfe, 0xce, 0x04, 0x20, 0x20, 0xa4, 0x22, 0x82, 0xb3, 0xe2, 0x5f,
	0xfa, 0x16, 0xab, 0x98, 0xad, 0x42, 0xa9, 0x8f, 0xf0, 0x74, 0xea, 0x23, 0xbc, 0xf3, 0xec, 0xf4,
	0xa2, 0x64, 0x9d, 0x5d, 0x94, 0xac, 0x9f, 0x17, 0x25, 0xeb, 0xf3, 0x65, 0x29, 0x73, 0x76, 0x59,
	0xca, 0xfc, 0xb8, 0x2c, 0x65, 0x8e, 0x36, 0x9a, 0x2d, 0xf9, 0xb6, 0xd3, 0xa8, 0x52, 0xee, 0xd5,
	0xcc, 0xe7, 0x5d, 0xff, 0xac, 0x0b, 0xf7, 0xa4, 0x16, 0xbe, 0xbc, 0x57, 0xbe, 0xf7, 0x8d, 0x29,
	0xf5, 0x79, 0xdf, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x37, 0x92, 0xb3, 0x88, 0x74, 0x08, 0x00,
	0x00,
}

func (m *AccessOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccessOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccessOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IdentifierTemplate) > 0 {
		i -= len(m.IdentifierTemplate)
		copy(dAtA[i:], m.IdentifierTemplate)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.IdentifierTemplate)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ResourceType != 0 {
		i = encodeVarintAccesscontrol(dAtA, i, uint64(m.ResourceType))
		i--
		dAtA[i] = 0x10
	}
	if m.AccessType != 0 {
		i = encodeVarintAccesscontrol(dAtA, i, uint64(m.AccessType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WasmAccessOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmAccessOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmAccessOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Selector) > 0 {
		i -= len(m.Selector)
		copy(dAtA[i:], m.Selector)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.Selector)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SelectorType != 0 {
		i = encodeVarintAccesscontrol(dAtA, i, uint64(m.SelectorType))
		i--
		dAtA[i] = 0x10
	}
	if m.Operation != nil {
		{
			size, err := m.Operation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WasmContractReference) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmContractReference) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmContractReference) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JsonTranslationTemplate) > 0 {
		i -= len(m.JsonTranslationTemplate)
		copy(dAtA[i:], m.JsonTranslationTemplate)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.JsonTranslationTemplate)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MessageName) > 0 {
		i -= len(m.MessageName)
		copy(dAtA[i:], m.MessageName)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.MessageName)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MessageType != 0 {
		i = encodeVarintAccesscontrol(dAtA, i, uint64(m.MessageType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WasmContractReferences) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmContractReferences) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmContractReferences) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractReferences) > 0 {
		for iNdEx := len(m.ContractReferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractReferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MessageName) > 0 {
		i -= len(m.MessageName)
		copy(dAtA[i:], m.MessageName)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.MessageName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WasmAccessOperations) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmAccessOperations) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmAccessOperations) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WasmOperations) > 0 {
		for iNdEx := len(m.WasmOperations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WasmOperations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MessageName) > 0 {
		i -= len(m.MessageName)
		copy(dAtA[i:], m.MessageName)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.MessageName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MessageDependencyMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageDependencyMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageDependencyMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DynamicEnabled {
		i--
		if m.DynamicEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.AccessOps) > 0 {
		for iNdEx := len(m.AccessOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccessOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MessageKey) > 0 {
		i -= len(m.MessageKey)
		copy(dAtA[i:], m.MessageKey)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.MessageKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WasmDependencyMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmDependencyMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmDependencyMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ResetReason) > 0 {
		i -= len(m.ResetReason)
		copy(dAtA[i:], m.ResetReason)
		i = encodeVarintAccesscontrol(dAtA, i, uint64(len(m.ResetReason)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ExecuteContractReferences) > 0 {
		for iNdEx := len(m.ExecuteContractReferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExecuteContractReferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.QueryContractReferences) > 0 {
		for iNdEx := len(m.QueryContractReferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.QueryContractReferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.BaseContractReferences) > 0 {
		for iNdEx := len(m.BaseContractReferences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BaseContractReferences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ExecuteAccessOps) > 0 {
		for iNdEx := len(m.ExecuteAccessOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExecuteAccessOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.QueryAccessOps) > 0 {
		for iNdEx := len(m.QueryAccessOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.QueryAccessOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.BaseAccessOps) > 0 {
		for iNdEx := len(m.BaseAccessOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BaseAccessOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccesscontrol(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintAccesscontrol(dAtA []byte, offset int, v uint64) int {
	offset -= sovAccesscontrol(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccessOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccessType != 0 {
		n += 1 + sovAccesscontrol(uint64(m.AccessType))
	}
	if m.ResourceType != 0 {
		n += 1 + sovAccesscontrol(uint64(m.ResourceType))
	}
	l = len(m.IdentifierTemplate)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	return n
}

func (m *WasmAccessOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Operation != nil {
		l = m.Operation.Size()
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	if m.SelectorType != 0 {
		n += 1 + sovAccesscontrol(uint64(m.SelectorType))
	}
	l = len(m.Selector)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	return n
}

func (m *WasmContractReference) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	if m.MessageType != 0 {
		n += 1 + sovAccesscontrol(uint64(m.MessageType))
	}
	l = len(m.MessageName)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	l = len(m.JsonTranslationTemplate)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	return n
}

func (m *WasmContractReferences) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MessageName)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	if len(m.ContractReferences) > 0 {
		for _, e := range m.ContractReferences {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	return n
}

func (m *WasmAccessOperations) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MessageName)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	if len(m.WasmOperations) > 0 {
		for _, e := range m.WasmOperations {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	return n
}

func (m *MessageDependencyMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MessageKey)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	if len(m.AccessOps) > 0 {
		for _, e := range m.AccessOps {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	if m.DynamicEnabled {
		n += 2
	}
	return n
}

func (m *WasmDependencyMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BaseAccessOps) > 0 {
		for _, e := range m.BaseAccessOps {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	if len(m.QueryAccessOps) > 0 {
		for _, e := range m.QueryAccessOps {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	if len(m.ExecuteAccessOps) > 0 {
		for _, e := range m.ExecuteAccessOps {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	if len(m.BaseContractReferences) > 0 {
		for _, e := range m.BaseContractReferences {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	if len(m.QueryContractReferences) > 0 {
		for _, e := range m.QueryContractReferences {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	if len(m.ExecuteContractReferences) > 0 {
		for _, e := range m.ExecuteContractReferences {
			l = e.Size()
			n += 1 + l + sovAccesscontrol(uint64(l))
		}
	}
	l = len(m.ResetReason)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovAccesscontrol(uint64(l))
	}
	return n
}

func sovAccesscontrol(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAccesscontrol(x uint64) (n int) {
	return sovAccesscontrol(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccessOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccessOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccessOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessType", wireType)
			}
			m.AccessType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccessType |= AccessType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceType", wireType)
			}
			m.ResourceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResourceType |= ResourceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentifierTemplate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentifierTemplate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmAccessOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmAccessOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmAccessOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Operation == nil {
				m.Operation = &AccessOperation{}
			}
			if err := m.Operation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectorType", wireType)
			}
			m.SelectorType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelectorType |= AccessOperationSelectorType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmContractReference) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmContractReference: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmContractReference: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageType", wireType)
			}
			m.MessageType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageType |= WasmMessageSubtype(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JsonTranslationTemplate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JsonTranslationTemplate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmContractReferences) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmContractReferences: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmContractReferences: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractReferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractReferences = append(m.ContractReferences, &WasmContractReference{})
			if err := m.ContractReferences[len(m.ContractReferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmAccessOperations) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmAccessOperations: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmAccessOperations: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmOperations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WasmOperations = append(m.WasmOperations, &WasmAccessOperation{})
			if err := m.WasmOperations[len(m.WasmOperations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessageDependencyMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageDependencyMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageDependencyMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessOps = append(m.AccessOps, AccessOperation{})
			if err := m.AccessOps[len(m.AccessOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DynamicEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DynamicEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmDependencyMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmDependencyMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmDependencyMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAccessOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseAccessOps = append(m.BaseAccessOps, &WasmAccessOperation{})
			if err := m.BaseAccessOps[len(m.BaseAccessOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryAccessOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryAccessOps = append(m.QueryAccessOps, &WasmAccessOperations{})
			if err := m.QueryAccessOps[len(m.QueryAccessOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteAccessOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecuteAccessOps = append(m.ExecuteAccessOps, &WasmAccessOperations{})
			if err := m.ExecuteAccessOps[len(m.ExecuteAccessOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseContractReferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseContractReferences = append(m.BaseContractReferences, &WasmContractReference{})
			if err := m.BaseContractReferences[len(m.BaseContractReferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryContractReferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryContractReferences = append(m.QueryContractReferences, &WasmContractReferences{})
			if err := m.QueryContractReferences[len(m.QueryContractReferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteContractReferences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecuteContractReferences = append(m.ExecuteContractReferences, &WasmContractReferences{})
			if err := m.ExecuteContractReferences[len(m.ExecuteContractReferences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResetReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResetReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccesscontrol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccesscontrol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccesscontrol(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccesscontrol
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccesscontrol
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccesscontrol
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAccesscontrol
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAccesscontrol
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAccesscontrol        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccesscontrol          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccesscontrol = fmt.Errorf("proto: unexpected end of group")
)
