// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol/v1beta1/legacy.proto

package accesscontrol

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LegacyAccessOperationWithSelector struct {
	Operation    *AccessOperation            `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	SelectorType AccessOperationSelectorType `protobuf:"varint,2,opt,name=selector_type,json=selectorType,proto3,enum=cosmos.accesscontrol.v1beta1.AccessOperationSelectorType" json:"selector_type,omitempty"`
	Selector     string                      `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (m *LegacyAccessOperationWithSelector) Reset()         { *m = LegacyAccessOperationWithSelector{} }
func (m *LegacyAccessOperationWithSelector) String() string { return proto.CompactTextString(m) }
func (*LegacyAccessOperationWithSelector) ProtoMessage()    {}
func (*LegacyAccessOperationWithSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_59e556e7b1c2d63a, []int{0}
}
func (m *LegacyAccessOperationWithSelector) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LegacyAccessOperationWithSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LegacyAccessOperationWithSelector.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LegacyAccessOperationWithSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LegacyAccessOperationWithSelector.Merge(m, src)
}
func (m *LegacyAccessOperationWithSelector) XXX_Size() int {
	return m.Size()
}
func (m *LegacyAccessOperationWithSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_LegacyAccessOperationWithSelector.DiscardUnknown(m)
}

var xxx_messageInfo_LegacyAccessOperationWithSelector proto.InternalMessageInfo

func (m *LegacyAccessOperationWithSelector) GetOperation() *AccessOperation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *LegacyAccessOperationWithSelector) GetSelectorType() AccessOperationSelectorType {
	if m != nil {
		return m.SelectorType
	}
	return AccessOperationSelectorType_NONE
}

func (m *LegacyAccessOperationWithSelector) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

type LegacyWasmDependencyMapping struct {
	Enabled         bool                                `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessOps       []LegacyAccessOperationWithSelector `protobuf:"bytes,2,rep,name=access_ops,json=accessOps,proto3" json:"access_ops"`
	ResetReason     string                              `protobuf:"bytes,3,opt,name=reset_reason,json=resetReason,proto3" json:"reset_reason,omitempty"`
	ContractAddress string                              `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *LegacyWasmDependencyMapping) Reset()         { *m = LegacyWasmDependencyMapping{} }
func (m *LegacyWasmDependencyMapping) String() string { return proto.CompactTextString(m) }
func (*LegacyWasmDependencyMapping) ProtoMessage()    {}
func (*LegacyWasmDependencyMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_59e556e7b1c2d63a, []int{1}
}
func (m *LegacyWasmDependencyMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LegacyWasmDependencyMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LegacyWasmDependencyMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LegacyWasmDependencyMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LegacyWasmDependencyMapping.Merge(m, src)
}
func (m *LegacyWasmDependencyMapping) XXX_Size() int {
	return m.Size()
}
func (m *LegacyWasmDependencyMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_LegacyWasmDependencyMapping.DiscardUnknown(m)
}

var xxx_messageInfo_LegacyWasmDependencyMapping proto.InternalMessageInfo

func (m *LegacyWasmDependencyMapping) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *LegacyWasmDependencyMapping) GetAccessOps() []LegacyAccessOperationWithSelector {
	if m != nil {
		return m.AccessOps
	}
	return nil
}

func (m *LegacyWasmDependencyMapping) GetResetReason() string {
	if m != nil {
		return m.ResetReason
	}
	return ""
}

func (m *LegacyWasmDependencyMapping) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*LegacyAccessOperationWithSelector)(nil), "cosmos.accesscontrol.v1beta1.LegacyAccessOperationWithSelector")
	proto.RegisterType((*LegacyWasmDependencyMapping)(nil), "cosmos.accesscontrol.v1beta1.LegacyWasmDependencyMapping")
}

func init() {
	proto.RegisterFile("cosmos/accesscontrol/v1beta1/legacy.proto", fileDescriptor_59e556e7b1c2d63a)
}

var fileDescriptor_59e556e7b1c2d63a = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0xc6, 0xbd, 0x77, 0x27, 0xb8, 0x6c, 0x8e, 0x3f, 0x5a, 0x51, 0x58, 0x01, 0x19, 0xdf, 0x55,
	0x3e, 0x89, 0xb3, 0x2f, 0xa1, 0xa2, 0x42, 0x89, 0xa8, 0xf8, 0x23, 0x24, 0x83, 0x14, 0x89, 0x02,
	0x6b, 0xbd, 0x1e, 0x39, 0x16, 0xce, 0xee, 0xca, 0xb3, 0x20, 0xf9, 0x2d, 0x78, 0xac, 0x94, 0x29,
	0xa9, 0x10, 0x4a, 0x4a, 0x78, 0x08, 0x94, 0xb5, 0x0d, 0x24, 0x85, 0xd1, 0x55, 0xf6, 0x7c, 0xfb,
	0x9b, 0x6f, 0xbf, 0xb1, 0x87, 0x5e, 0x0a, 0x85, 0x4b, 0x85, 0x11, 0x17, 0x02, 0x10, 0x85, 0x92,
	0xa6, 0x52, 0x65, 0xf4, 0x65, 0x9c, 0x82, 0xe1, 0xe3, 0xa8, 0x84, 0x9c, 0x8b, 0x3a, 0xd4, 0x95,
	0x32, 0x8a, 0x3d, 0x6a, 0xd0, 0x70, 0x0f, 0x0d, 0x5b, 0x74, 0xf4, 0x20, 0x57, 0xb9, 0xb2, 0x60,
	0xb4, 0x7b, 0x6b, 0x7a, 0x46, 0x4f, 0x7a, 0xed, 0x85, 0x92, 0x68, 0xb8, 0x34, 0xd8, 0xd2, 0xd7,
	0xbd, 0xf4, 0xfe, 0xbd, 0xb6, 0xe3, 0xe2, 0x17, 0xa1, 0xe7, 0xaf, 0x6d, 0xc8, 0xa9, 0x3d, 0x7d,
	0xab, 0xa1, 0xe2, 0xa6, 0x50, 0x72, 0x5e, 0x98, 0xc5, 0x3b, 0x28, 0x41, 0x18, 0x55, 0xb1, 0x57,
	0x74, 0xa0, 0xba, 0x03, 0x97, 0xf8, 0x24, 0x18, 0x4e, 0xae, 0xc2, 0xbe, 0x69, 0xc2, 0x03, 0xb7,
	0xf8, 0x6f, 0x3f, 0xfb, 0x48, 0xef, 0x60, 0x6b, 0x9c, 0x98, 0x5a, 0x83, 0x7b, 0xe4, 0x93, 0xe0,
	0xee, 0xe4, 0xd9, 0x8d, 0x0c, 0xbb, 0x68, 0xef, 0x6b, 0x0d, 0xf1, 0x19, 0xfe, 0x53, 0xb1, 0x11,
	0x3d, 0xed, 0x6a, 0xf7, 0xd8, 0x27, 0xc1, 0x20, 0xfe, 0x53, 0x5f, 0xfc, 0x24, 0xf4, 0x61, 0x33,
	0xee, 0x9c, 0xe3, 0xf2, 0x05, 0x68, 0x90, 0x19, 0x48, 0x51, 0xbf, 0xe1, 0x5a, 0x17, 0x32, 0x67,
	0x2e, 0xbd, 0x0d, 0x92, 0xa7, 0x25, 0x64, 0x76, 0xcc, 0xd3, 0xb8, 0x2b, 0x59, 0x46, 0x69, 0x13,
	0x2c, 0x51, 0x1a, 0xdd, 0x23, 0xff, 0x38, 0x18, 0x4e, 0x9e, 0xf7, 0x47, 0xfe, 0xef, 0x77, 0x9d,
	0x9d, 0xac, 0xbe, 0x3f, 0x76, 0xe2, 0x01, 0x6f, 0x11, 0x64, 0xe7, 0xf4, 0xac, 0x02, 0x04, 0x93,
	0x54, 0xc0, 0x51, 0xc9, 0x36, 0xff, 0xd0, 0x6a, 0xb1, 0x95, 0xd8, 0x25, 0xbd, 0x6f, 0x2f, 0xe2,
	0xc2, 0x24, 0x3c, 0xcb, 0x2a, 0x40, 0x74, 0x4f, 0x2c, 0x76, 0xaf, 0xd3, 0xa7, 0x8d, 0x3c, 0x7b,
	0xb9, 0xda, 0x78, 0x64, 0xbd, 0xf1, 0xc8, 0x8f, 0x8d, 0x47, 0xbe, 0x6e, 0x3d, 0x67, 0xbd, 0xf5,
	0x9c, 0x6f, 0x5b, 0xcf, 0xf9, 0x70, 0x9d, 0x17, 0x66, 0xf1, 0x39, 0x0d, 0x85, 0x5a, 0x46, 0xed,
	0xce, 0x34, 0x8f, 0x2b, 0xcc, 0x3e, 0x45, 0xbb, 0xbf, 0x72, 0xb0, 0x44, 0xe9, 0x2d, 0xbb, 0x2f,
	0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x19, 0x72, 0x2c, 0xaa, 0xf0, 0x02, 0x00, 0x00,
}

func (m *LegacyAccessOperationWithSelector) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LegacyAccessOperationWithSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LegacyAccessOperationWithSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Selector) > 0 {
		i -= len(m.Selector)
		copy(dAtA[i:], m.Selector)
		i = encodeVarintLegacy(dAtA, i, uint64(len(m.Selector)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SelectorType != 0 {
		i = encodeVarintLegacy(dAtA, i, uint64(m.SelectorType))
		i--
		dAtA[i] = 0x10
	}
	if m.Operation != nil {
		{
			size, err := m.Operation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLegacy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LegacyWasmDependencyMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LegacyWasmDependencyMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LegacyWasmDependencyMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintLegacy(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ResetReason) > 0 {
		i -= len(m.ResetReason)
		copy(dAtA[i:], m.ResetReason)
		i = encodeVarintLegacy(dAtA, i, uint64(len(m.ResetReason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccessOps) > 0 {
		for iNdEx := len(m.AccessOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccessOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLegacy(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLegacy(dAtA []byte, offset int, v uint64) int {
	offset -= sovLegacy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LegacyAccessOperationWithSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Operation != nil {
		l = m.Operation.Size()
		n += 1 + l + sovLegacy(uint64(l))
	}
	if m.SelectorType != 0 {
		n += 1 + sovLegacy(uint64(m.SelectorType))
	}
	l = len(m.Selector)
	if l > 0 {
		n += 1 + l + sovLegacy(uint64(l))
	}
	return n
}

func (m *LegacyWasmDependencyMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	if len(m.AccessOps) > 0 {
		for _, e := range m.AccessOps {
			l = e.Size()
			n += 1 + l + sovLegacy(uint64(l))
		}
	}
	l = len(m.ResetReason)
	if l > 0 {
		n += 1 + l + sovLegacy(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovLegacy(uint64(l))
	}
	return n
}

func sovLegacy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLegacy(x uint64) (n int) {
	return sovLegacy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LegacyAccessOperationWithSelector) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LegacyAccessOperationWithSelector: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LegacyAccessOperationWithSelector: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLegacy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLegacy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Operation == nil {
				m.Operation = &AccessOperation{}
			}
			if err := m.Operation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectorType", wireType)
			}
			m.SelectorType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelectorType |= AccessOperationSelectorType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLegacy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LegacyWasmDependencyMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LegacyWasmDependencyMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LegacyWasmDependencyMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLegacy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLegacy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessOps = append(m.AccessOps, LegacyAccessOperationWithSelector{})
			if err := m.AccessOps[len(m.AccessOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResetReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResetReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLegacy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLegacy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLegacy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLegacy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLegacy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLegacy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLegacy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLegacy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLegacy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLegacy = fmt.Errorf("proto: unexpected end of group")
)
