// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol_x/v1beta1/query.proto

package accesscontrol

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	// params defines the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type ResourceDependencyMappingFromMessageKeyRequest struct {
	MessageKey string `protobuf:"bytes,1,opt,name=message_key,json=messageKey,proto3" json:"message_key,omitempty" yaml:"message_key"`
}

func (m *ResourceDependencyMappingFromMessageKeyRequest) Reset() {
	*m = ResourceDependencyMappingFromMessageKeyRequest{}
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) String() string {
	return proto.CompactTextString(m)
}
func (*ResourceDependencyMappingFromMessageKeyRequest) ProtoMessage() {}
func (*ResourceDependencyMappingFromMessageKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{2}
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResourceDependencyMappingFromMessageKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDependencyMappingFromMessageKeyRequest.Merge(m, src)
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDependencyMappingFromMessageKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDependencyMappingFromMessageKeyRequest proto.InternalMessageInfo

func (m *ResourceDependencyMappingFromMessageKeyRequest) GetMessageKey() string {
	if m != nil {
		return m.MessageKey
	}
	return ""
}

type ResourceDependencyMappingFromMessageKeyResponse struct {
	MessageDependencyMapping MessageDependencyMapping `protobuf:"bytes,1,opt,name=message_dependency_mapping,json=messageDependencyMapping,proto3" json:"message_dependency_mapping" yaml:"message_dependency_mapping"`
}

func (m *ResourceDependencyMappingFromMessageKeyResponse) Reset() {
	*m = ResourceDependencyMappingFromMessageKeyResponse{}
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) String() string {
	return proto.CompactTextString(m)
}
func (*ResourceDependencyMappingFromMessageKeyResponse) ProtoMessage() {}
func (*ResourceDependencyMappingFromMessageKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{3}
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResourceDependencyMappingFromMessageKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDependencyMappingFromMessageKeyResponse.Merge(m, src)
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDependencyMappingFromMessageKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDependencyMappingFromMessageKeyResponse proto.InternalMessageInfo

func (m *ResourceDependencyMappingFromMessageKeyResponse) GetMessageDependencyMapping() MessageDependencyMapping {
	if m != nil {
		return m.MessageDependencyMapping
	}
	return MessageDependencyMapping{}
}

type WasmDependencyMappingRequest struct {
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" yaml:"contract_address"`
}

func (m *WasmDependencyMappingRequest) Reset()         { *m = WasmDependencyMappingRequest{} }
func (m *WasmDependencyMappingRequest) String() string { return proto.CompactTextString(m) }
func (*WasmDependencyMappingRequest) ProtoMessage()    {}
func (*WasmDependencyMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{4}
}
func (m *WasmDependencyMappingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmDependencyMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmDependencyMappingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmDependencyMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmDependencyMappingRequest.Merge(m, src)
}
func (m *WasmDependencyMappingRequest) XXX_Size() int {
	return m.Size()
}
func (m *WasmDependencyMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmDependencyMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WasmDependencyMappingRequest proto.InternalMessageInfo

func (m *WasmDependencyMappingRequest) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type WasmDependencyMappingResponse struct {
	WasmDependencyMapping WasmDependencyMapping `protobuf:"bytes,1,opt,name=wasm_dependency_mapping,json=wasmDependencyMapping,proto3" json:"wasm_dependency_mapping" yaml:"wasm_dependency_mapping"`
}

func (m *WasmDependencyMappingResponse) Reset()         { *m = WasmDependencyMappingResponse{} }
func (m *WasmDependencyMappingResponse) String() string { return proto.CompactTextString(m) }
func (*WasmDependencyMappingResponse) ProtoMessage()    {}
func (*WasmDependencyMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{5}
}
func (m *WasmDependencyMappingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WasmDependencyMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WasmDependencyMappingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WasmDependencyMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmDependencyMappingResponse.Merge(m, src)
}
func (m *WasmDependencyMappingResponse) XXX_Size() int {
	return m.Size()
}
func (m *WasmDependencyMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmDependencyMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WasmDependencyMappingResponse proto.InternalMessageInfo

func (m *WasmDependencyMappingResponse) GetWasmDependencyMapping() WasmDependencyMapping {
	if m != nil {
		return m.WasmDependencyMapping
	}
	return WasmDependencyMapping{}
}

type ListResourceDependencyMappingRequest struct {
}

func (m *ListResourceDependencyMappingRequest) Reset()         { *m = ListResourceDependencyMappingRequest{} }
func (m *ListResourceDependencyMappingRequest) String() string { return proto.CompactTextString(m) }
func (*ListResourceDependencyMappingRequest) ProtoMessage()    {}
func (*ListResourceDependencyMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{6}
}
func (m *ListResourceDependencyMappingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListResourceDependencyMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListResourceDependencyMappingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListResourceDependencyMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourceDependencyMappingRequest.Merge(m, src)
}
func (m *ListResourceDependencyMappingRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListResourceDependencyMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourceDependencyMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourceDependencyMappingRequest proto.InternalMessageInfo

type ListResourceDependencyMappingResponse struct {
	MessageDependencyMappingList []MessageDependencyMapping `protobuf:"bytes,1,rep,name=message_dependency_mapping_list,json=messageDependencyMappingList,proto3" json:"message_dependency_mapping_list" yaml:"message_dependency_mapping_list"`
}

func (m *ListResourceDependencyMappingResponse) Reset()         { *m = ListResourceDependencyMappingResponse{} }
func (m *ListResourceDependencyMappingResponse) String() string { return proto.CompactTextString(m) }
func (*ListResourceDependencyMappingResponse) ProtoMessage()    {}
func (*ListResourceDependencyMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{7}
}
func (m *ListResourceDependencyMappingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListResourceDependencyMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListResourceDependencyMappingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListResourceDependencyMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourceDependencyMappingResponse.Merge(m, src)
}
func (m *ListResourceDependencyMappingResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListResourceDependencyMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourceDependencyMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourceDependencyMappingResponse proto.InternalMessageInfo

func (m *ListResourceDependencyMappingResponse) GetMessageDependencyMappingList() []MessageDependencyMapping {
	if m != nil {
		return m.MessageDependencyMappingList
	}
	return nil
}

type ListWasmDependencyMappingRequest struct {
}

func (m *ListWasmDependencyMappingRequest) Reset()         { *m = ListWasmDependencyMappingRequest{} }
func (m *ListWasmDependencyMappingRequest) String() string { return proto.CompactTextString(m) }
func (*ListWasmDependencyMappingRequest) ProtoMessage()    {}
func (*ListWasmDependencyMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{8}
}
func (m *ListWasmDependencyMappingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListWasmDependencyMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListWasmDependencyMappingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListWasmDependencyMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWasmDependencyMappingRequest.Merge(m, src)
}
func (m *ListWasmDependencyMappingRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListWasmDependencyMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWasmDependencyMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWasmDependencyMappingRequest proto.InternalMessageInfo

type ListWasmDependencyMappingResponse struct {
	WasmDependencyMappingList []WasmDependencyMapping `protobuf:"bytes,1,rep,name=wasm_dependency_mapping_list,json=wasmDependencyMappingList,proto3" json:"wasm_dependency_mapping_list" yaml:"wasm_dependency_mapping_list"`
}

func (m *ListWasmDependencyMappingResponse) Reset()         { *m = ListWasmDependencyMappingResponse{} }
func (m *ListWasmDependencyMappingResponse) String() string { return proto.CompactTextString(m) }
func (*ListWasmDependencyMappingResponse) ProtoMessage()    {}
func (*ListWasmDependencyMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a48083d82035a81, []int{9}
}
func (m *ListWasmDependencyMappingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListWasmDependencyMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListWasmDependencyMappingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListWasmDependencyMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWasmDependencyMappingResponse.Merge(m, src)
}
func (m *ListWasmDependencyMappingResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListWasmDependencyMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWasmDependencyMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWasmDependencyMappingResponse proto.InternalMessageInfo

func (m *ListWasmDependencyMappingResponse) GetWasmDependencyMappingList() []WasmDependencyMapping {
	if m != nil {
		return m.WasmDependencyMappingList
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.accesscontrol_x.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.accesscontrol_x.v1beta1.QueryParamsResponse")
	proto.RegisterType((*ResourceDependencyMappingFromMessageKeyRequest)(nil), "cosmos.accesscontrol_x.v1beta1.ResourceDependencyMappingFromMessageKeyRequest")
	proto.RegisterType((*ResourceDependencyMappingFromMessageKeyResponse)(nil), "cosmos.accesscontrol_x.v1beta1.ResourceDependencyMappingFromMessageKeyResponse")
	proto.RegisterType((*WasmDependencyMappingRequest)(nil), "cosmos.accesscontrol_x.v1beta1.WasmDependencyMappingRequest")
	proto.RegisterType((*WasmDependencyMappingResponse)(nil), "cosmos.accesscontrol_x.v1beta1.WasmDependencyMappingResponse")
	proto.RegisterType((*ListResourceDependencyMappingRequest)(nil), "cosmos.accesscontrol_x.v1beta1.ListResourceDependencyMappingRequest")
	proto.RegisterType((*ListResourceDependencyMappingResponse)(nil), "cosmos.accesscontrol_x.v1beta1.ListResourceDependencyMappingResponse")
	proto.RegisterType((*ListWasmDependencyMappingRequest)(nil), "cosmos.accesscontrol_x.v1beta1.ListWasmDependencyMappingRequest")
	proto.RegisterType((*ListWasmDependencyMappingResponse)(nil), "cosmos.accesscontrol_x.v1beta1.ListWasmDependencyMappingResponse")
}

func init() {
	proto.RegisterFile("cosmos/accesscontrol_x/v1beta1/query.proto", fileDescriptor_2a48083d82035a81)
}

var fileDescriptor_2a48083d82035a81 = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x4f, 0xd4, 0x40,
	0x14, 0xdf, 0x41, 0x25, 0x61, 0x38, 0x68, 0x46, 0x10, 0x58, 0x97, 0x2e, 0x8c, 0xba, 0x88, 0x7f,
	0x5a, 0x59, 0x62, 0x34, 0x46, 0xa2, 0xac, 0x40, 0xa2, 0x88, 0x7f, 0xea, 0xc1, 0x44, 0x62, 0x36,
	0xb3, 0xdd, 0xa1, 0x36, 0x6c, 0x3b, 0xa5, 0xd3, 0x15, 0x37, 0x84, 0x8b, 0x9f, 0xc0, 0xc4, 0xf8,
	0x01, 0xd4, 0xbb, 0x1c, 0xfd, 0x0a, 0x78, 0x23, 0x31, 0x26, 0x7a, 0xd9, 0x18, 0x30, 0x31, 0x5e,
	0xb9, 0x78, 0x35, 0x6d, 0x67, 0xc9, 0xfe, 0x6b, 0xbb, 0x80, 0xa7, 0xee, 0xbe, 0x79, 0xef, 0xfd,
	0xde, 0xef, 0xf7, 0xde, 0xbc, 0x16, 0x5e, 0xd0, 0x18, 0x37, 0x19, 0x57, 0x88, 0xa6, 0x51, 0xce,
	0x35, 0x66, 0xb9, 0x0e, 0x2b, 0xe5, 0x5f, 0x29, 0x2f, 0x27, 0x0a, 0xd4, 0x25, 0x13, 0xca, 0x4a,
	0x99, 0x3a, 0x15, 0xd9, 0x76, 0x98, 0xcb, 0x90, 0x14, 0xf8, 0xca, 0x4d, 0xbe, 0xb2, 0xf0, 0x4d,
	0xf6, 0xe9, 0x4c, 0x67, 0xbe, 0xab, 0xe2, 0xfd, 0x0a, 0xa2, 0x92, 0x29, 0x9d, 0x31, 0xbd, 0x44,
	0x15, 0x62, 0x1b, 0x0a, 0xb1, 0x2c, 0xe6, 0x12, 0xd7, 0x60, 0x16, 0x17, 0xa7, 0x35, 0xfc, 0x02,
	0xe1, 0x34, 0x00, 0xdb, 0x83, 0xb6, 0x89, 0x6e, 0x58, 0xbe, 0xb3, 0xf0, 0xcd, 0xc6, 0xd4, 0xda,
	0x60, 0x17, 0x31, 0x97, 0x62, 0x62, 0x74, 0x6a, 0x51, 0x6e, 0x88, 0x6a, 0x70, 0x1f, 0x44, 0x8f,
	0xbd, 0x1a, 0x1e, 0x11, 0x87, 0x98, 0x5c, 0xa5, 0x2b, 0x65, 0xca, 0x5d, 0xbc, 0x08, 0x4f, 0x36,
	0x58, 0xb9, 0xcd, 0x2c, 0x4e, 0xd1, 0x0c, 0xec, 0xb6, 0x7d, 0xcb, 0x20, 0x18, 0x01, 0xe7, 0x7b,
	0xb3, 0x19, 0x39, 0x5a, 0x1f, 0x39, 0x88, 0xcf, 0x1d, 0xdd, 0xac, 0xa6, 0x13, 0xaa, 0x88, 0xc5,
	0x06, 0x94, 0x55, 0xca, 0x59, 0xd9, 0xd1, 0xe8, 0x0c, 0xb5, 0xa9, 0x55, 0xa4, 0x96, 0x56, 0x59,
	0x20, 0xb6, 0x6d, 0x58, 0xfa, 0x9c, 0xc3, 0xcc, 0x05, 0xca, 0x39, 0xd1, 0xe9, 0x3c, 0xad, 0x88,
	0x72, 0xd0, 0x35, 0xd8, 0x6b, 0x06, 0xc6, 0xfc, 0x32, 0xad, 0xf8, 0xe0, 0x3d, 0xb9, 0x53, 0xbb,
	0xd5, 0x34, 0xaa, 0x10, 0xb3, 0x74, 0x03, 0xd7, 0x1d, 0x62, 0x15, 0x9a, 0x7b, 0xf1, 0xf8, 0x1b,
	0x80, 0x4a, 0xc7, 0x58, 0x82, 0xe4, 0x7b, 0x00, 0x93, 0xb5, 0x84, 0xc5, 0xbd, 0x98, 0xbc, 0x19,
	0x04, 0x09, 0xe6, 0xd7, 0xe3, 0x98, 0x8b, 0xc4, 0x2d, 0xa0, 0xb9, 0x71, 0x4f, 0x8b, 0xdd, 0x6a,
	0x7a, 0xb4, 0xb1, 0xf4, 0x56, 0x24, 0xac, 0x0e, 0x9a, 0x21, 0x49, 0xf0, 0x12, 0x4c, 0x3d, 0x25,
	0xdc, 0x6c, 0x39, 0xa8, 0x09, 0x36, 0x07, 0x4f, 0xf8, 0x25, 0x11, 0xcd, 0xcd, 0x93, 0x62, 0xd1,
	0xa1, 0x9c, 0x0b, 0xd5, 0x4e, 0xef, 0x56, 0xd3, 0x03, 0x01, 0x74, 0xb3, 0x07, 0x56, 0x8f, 0xd7,
	0x4c, 0xd3, 0xc2, 0xf2, 0x19, 0xc0, 0xe1, 0x10, 0x20, 0xa1, 0xd6, 0x3b, 0x00, 0x07, 0x56, 0x09,
	0x37, 0xc3, 0xa5, 0xba, 0x1a, 0x27, 0x55, 0x5b, 0x80, 0x5c, 0x46, 0xe8, 0x24, 0x05, 0xc5, 0x86,
	0x60, 0x60, 0xb5, 0x7f, 0xb5, 0x5d, 0x38, 0xce, 0xc0, 0xb3, 0xf7, 0x0d, 0xee, 0x86, 0x36, 0xbf,
	0x36, 0xe9, 0x3f, 0x00, 0x3c, 0x17, 0xe3, 0x28, 0x98, 0x6e, 0x00, 0x98, 0x0e, 0xef, 0x56, 0xbe,
	0x64, 0x70, 0x77, 0x10, 0x8c, 0x1c, 0x39, 0xd4, 0x70, 0xc8, 0x82, 0x74, 0x26, 0x6e, 0x38, 0x7c,
	0x38, 0xac, 0xa6, 0xc2, 0x26, 0xc4, 0xa3, 0x84, 0x31, 0x1c, 0xf1, 0x9e, 0x51, 0x93, 0x82, 0xbf,
	0x00, 0x38, 0x1a, 0xe1, 0x24, 0xb8, 0x7f, 0x04, 0x30, 0x15, 0xd2, 0x81, 0x7a, 0xe2, 0x07, 0x6c,
	0xf5, 0x45, 0xc1, 0xfa, 0x4c, 0x64, 0xab, 0x05, 0xe5, 0xa1, 0xb6, 0xfd, 0xf6, 0x28, 0x64, 0x3f,
	0xf5, 0xc0, 0x63, 0xfe, 0xda, 0x42, 0x1f, 0x00, 0xec, 0x0e, 0x76, 0x0f, 0xca, 0xc6, 0xd5, 0xd4,
	0xba, 0xfe, 0x92, 0x93, 0xfb, 0x8a, 0x09, 0x34, 0xc2, 0xca, 0xeb, 0xaf, 0xbf, 0xde, 0x76, 0x8d,
	0xa3, 0x31, 0x45, 0x2c, 0xe0, 0xe0, 0x71, 0x99, 0x17, 0x97, 0x1b, 0x77, 0xb1, 0x12, 0xec, 0x41,
	0xb4, 0xd1, 0x05, 0xc7, 0x3a, 0x5c, 0x4e, 0xe8, 0x41, 0x5c, 0x45, 0xfb, 0xdb, 0xa8, 0xc9, 0x87,
	0xff, 0x2d, 0x9f, 0x60, 0xaf, 0xf9, 0xec, 0x9f, 0xa3, 0xc5, 0x58, 0xf6, 0x8e, 0xc8, 0xdc, 0xae,
	0xc5, 0x4b, 0x0e, 0x33, 0xf3, 0x75, 0xdb, 0x5c, 0x59, 0xab, 0xfb, 0xb3, 0x8e, 0xfe, 0x02, 0x38,
	0x1c, 0x79, 0x59, 0xd1, 0x4c, 0x1c, 0xaf, 0x4e, 0x96, 0x42, 0x72, 0xf6, 0x90, 0x59, 0x84, 0x26,
	0x77, 0x7d, 0x4d, 0xee, 0xa0, 0xe9, 0x58, 0x4d, 0xbc, 0xd1, 0xce, 0x47, 0x08, 0x83, 0xfe, 0x00,
	0xd8, 0xdf, 0xf6, 0xf2, 0xa0, 0x9b, 0x07, 0xba, 0x73, 0x35, 0xa6, 0x53, 0x07, 0x8c, 0x16, 0x0c,
	0x9f, 0xf8, 0x0c, 0x17, 0xd0, 0x7c, 0x2c, 0xc3, 0x90, 0x4b, 0xad, 0xac, 0x35, 0xbf, 0x85, 0xd6,
	0xd1, 0x6f, 0x00, 0x87, 0x42, 0x57, 0x12, 0xba, 0xdd, 0x49, 0x6f, 0x22, 0x39, 0x4f, 0x1f, 0x22,
	0x83, 0xe0, 0x3d, 0xeb, 0xf3, 0xbe, 0x85, 0xa6, 0x3a, 0xeb, 0x6c, 0x08, 0xf9, 0xdc, 0xbd, 0xcd,
	0x6d, 0x09, 0x6c, 0x6d, 0x4b, 0xe0, 0xe7, 0xb6, 0x04, 0xde, 0xec, 0x48, 0x89, 0xad, 0x1d, 0x29,
	0xf1, 0x7d, 0x47, 0x4a, 0x3c, 0xbb, 0xa2, 0x1b, 0xee, 0x8b, 0x72, 0x41, 0xd6, 0x98, 0xd9, 0x06,
	0xc2, 0xad, 0xd8, 0xb4, 0xe9, 0x03, 0xaf, 0xd0, 0xed, 0x7f, 0xcf, 0x4d, 0xfe, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0x6b, 0x63, 0x9b, 0xdf, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	ResourceDependencyMappingFromMessageKey(ctx context.Context, in *ResourceDependencyMappingFromMessageKeyRequest, opts ...grpc.CallOption) (*ResourceDependencyMappingFromMessageKeyResponse, error)
	ListResourceDependencyMapping(ctx context.Context, in *ListResourceDependencyMappingRequest, opts ...grpc.CallOption) (*ListResourceDependencyMappingResponse, error)
	WasmDependencyMapping(ctx context.Context, in *WasmDependencyMappingRequest, opts ...grpc.CallOption) (*WasmDependencyMappingResponse, error)
	ListWasmDependencyMapping(ctx context.Context, in *ListWasmDependencyMappingRequest, opts ...grpc.CallOption) (*ListWasmDependencyMappingResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.accesscontrol_x.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ResourceDependencyMappingFromMessageKey(ctx context.Context, in *ResourceDependencyMappingFromMessageKeyRequest, opts ...grpc.CallOption) (*ResourceDependencyMappingFromMessageKeyResponse, error) {
	out := new(ResourceDependencyMappingFromMessageKeyResponse)
	err := c.cc.Invoke(ctx, "/cosmos.accesscontrol_x.v1beta1.Query/ResourceDependencyMappingFromMessageKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListResourceDependencyMapping(ctx context.Context, in *ListResourceDependencyMappingRequest, opts ...grpc.CallOption) (*ListResourceDependencyMappingResponse, error) {
	out := new(ListResourceDependencyMappingResponse)
	err := c.cc.Invoke(ctx, "/cosmos.accesscontrol_x.v1beta1.Query/ListResourceDependencyMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WasmDependencyMapping(ctx context.Context, in *WasmDependencyMappingRequest, opts ...grpc.CallOption) (*WasmDependencyMappingResponse, error) {
	out := new(WasmDependencyMappingResponse)
	err := c.cc.Invoke(ctx, "/cosmos.accesscontrol_x.v1beta1.Query/WasmDependencyMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListWasmDependencyMapping(ctx context.Context, in *ListWasmDependencyMappingRequest, opts ...grpc.CallOption) (*ListWasmDependencyMappingResponse, error) {
	out := new(ListWasmDependencyMappingResponse)
	err := c.cc.Invoke(ctx, "/cosmos.accesscontrol_x.v1beta1.Query/ListWasmDependencyMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	ResourceDependencyMappingFromMessageKey(context.Context, *ResourceDependencyMappingFromMessageKeyRequest) (*ResourceDependencyMappingFromMessageKeyResponse, error)
	ListResourceDependencyMapping(context.Context, *ListResourceDependencyMappingRequest) (*ListResourceDependencyMappingResponse, error)
	WasmDependencyMapping(context.Context, *WasmDependencyMappingRequest) (*WasmDependencyMappingResponse, error)
	ListWasmDependencyMapping(context.Context, *ListWasmDependencyMappingRequest) (*ListWasmDependencyMappingResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ResourceDependencyMappingFromMessageKey(ctx context.Context, req *ResourceDependencyMappingFromMessageKeyRequest) (*ResourceDependencyMappingFromMessageKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceDependencyMappingFromMessageKey not implemented")
}
func (*UnimplementedQueryServer) ListResourceDependencyMapping(ctx context.Context, req *ListResourceDependencyMappingRequest) (*ListResourceDependencyMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceDependencyMapping not implemented")
}
func (*UnimplementedQueryServer) WasmDependencyMapping(ctx context.Context, req *WasmDependencyMappingRequest) (*WasmDependencyMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WasmDependencyMapping not implemented")
}
func (*UnimplementedQueryServer) ListWasmDependencyMapping(ctx context.Context, req *ListWasmDependencyMappingRequest) (*ListWasmDependencyMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWasmDependencyMapping not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.accesscontrol_x.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ResourceDependencyMappingFromMessageKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceDependencyMappingFromMessageKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ResourceDependencyMappingFromMessageKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.accesscontrol_x.v1beta1.Query/ResourceDependencyMappingFromMessageKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ResourceDependencyMappingFromMessageKey(ctx, req.(*ResourceDependencyMappingFromMessageKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListResourceDependencyMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceDependencyMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListResourceDependencyMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.accesscontrol_x.v1beta1.Query/ListResourceDependencyMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListResourceDependencyMapping(ctx, req.(*ListResourceDependencyMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WasmDependencyMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WasmDependencyMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WasmDependencyMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.accesscontrol_x.v1beta1.Query/WasmDependencyMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WasmDependencyMapping(ctx, req.(*WasmDependencyMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListWasmDependencyMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWasmDependencyMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListWasmDependencyMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.accesscontrol_x.v1beta1.Query/ListWasmDependencyMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListWasmDependencyMapping(ctx, req.(*ListWasmDependencyMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.accesscontrol_x.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ResourceDependencyMappingFromMessageKey",
			Handler:    _Query_ResourceDependencyMappingFromMessageKey_Handler,
		},
		{
			MethodName: "ListResourceDependencyMapping",
			Handler:    _Query_ListResourceDependencyMapping_Handler,
		},
		{
			MethodName: "WasmDependencyMapping",
			Handler:    _Query_WasmDependencyMapping_Handler,
		},
		{
			MethodName: "ListWasmDependencyMapping",
			Handler:    _Query_ListWasmDependencyMapping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/accesscontrol_x/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ResourceDependencyMappingFromMessageKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceDependencyMappingFromMessageKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceDependencyMappingFromMessageKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageKey) > 0 {
		i -= len(m.MessageKey)
		copy(dAtA[i:], m.MessageKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MessageKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResourceDependencyMappingFromMessageKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceDependencyMappingFromMessageKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceDependencyMappingFromMessageKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MessageDependencyMapping.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *WasmDependencyMappingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmDependencyMappingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmDependencyMappingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WasmDependencyMappingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WasmDependencyMappingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WasmDependencyMappingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WasmDependencyMapping.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ListResourceDependencyMappingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListResourceDependencyMappingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListResourceDependencyMappingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListResourceDependencyMappingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListResourceDependencyMappingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListResourceDependencyMappingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageDependencyMappingList) > 0 {
		for iNdEx := len(m.MessageDependencyMappingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageDependencyMappingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ListWasmDependencyMappingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListWasmDependencyMappingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListWasmDependencyMappingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListWasmDependencyMappingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListWasmDependencyMappingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListWasmDependencyMappingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WasmDependencyMappingList) > 0 {
		for iNdEx := len(m.WasmDependencyMappingList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WasmDependencyMappingList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *ResourceDependencyMappingFromMessageKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MessageKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *ResourceDependencyMappingFromMessageKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MessageDependencyMapping.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *WasmDependencyMappingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *WasmDependencyMappingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.WasmDependencyMapping.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *ListResourceDependencyMappingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListResourceDependencyMappingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MessageDependencyMappingList) > 0 {
		for _, e := range m.MessageDependencyMappingList {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *ListWasmDependencyMappingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListWasmDependencyMappingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.WasmDependencyMappingList) > 0 {
		for _, e := range m.WasmDependencyMappingList {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResourceDependencyMappingFromMessageKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResourceDependencyMappingFromMessageKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResourceDependencyMappingFromMessageKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResourceDependencyMappingFromMessageKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResourceDependencyMappingFromMessageKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResourceDependencyMappingFromMessageKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MessageDependencyMapping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmDependencyMappingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmDependencyMappingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmDependencyMappingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WasmDependencyMappingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WasmDependencyMappingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WasmDependencyMappingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmDependencyMapping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListResourceDependencyMappingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListResourceDependencyMappingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListResourceDependencyMappingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListResourceDependencyMappingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListResourceDependencyMappingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListResourceDependencyMappingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMappingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageDependencyMappingList = append(m.MessageDependencyMappingList, MessageDependencyMapping{})
			if err := m.MessageDependencyMappingList[len(m.MessageDependencyMappingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListWasmDependencyMappingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListWasmDependencyMappingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListWasmDependencyMappingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListWasmDependencyMappingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListWasmDependencyMappingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListWasmDependencyMappingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDependencyMappingList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WasmDependencyMappingList = append(m.WasmDependencyMappingList, WasmDependencyMapping{})
			if err := m.WasmDependencyMappingList[len(m.WasmDependencyMappingList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
