// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol_x/v1beta1/tx.proto

package accesscontrol

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RegisterWasmDependencyJSONFile struct {
	WasmDependencyMapping WasmDependencyMapping `protobuf:"bytes,1,opt,name=wasm_dependency_mapping,json=wasmDependencyMapping,proto3" json:"wasm_dependency_mapping" yaml:"wasm_dependency_mapping"`
}

func (m *RegisterWasmDependencyJSONFile) Reset()         { *m = RegisterWasmDependencyJSONFile{} }
func (m *RegisterWasmDependencyJSONFile) String() string { return proto.CompactTextString(m) }
func (*RegisterWasmDependencyJSONFile) ProtoMessage()    {}
func (*RegisterWasmDependencyJSONFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9f3f1912ca0e01d, []int{0}
}
func (m *RegisterWasmDependencyJSONFile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterWasmDependencyJSONFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterWasmDependencyJSONFile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterWasmDependencyJSONFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWasmDependencyJSONFile.Merge(m, src)
}
func (m *RegisterWasmDependencyJSONFile) XXX_Size() int {
	return m.Size()
}
func (m *RegisterWasmDependencyJSONFile) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWasmDependencyJSONFile.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWasmDependencyJSONFile proto.InternalMessageInfo

func (m *RegisterWasmDependencyJSONFile) GetWasmDependencyMapping() WasmDependencyMapping {
	if m != nil {
		return m.WasmDependencyMapping
	}
	return WasmDependencyMapping{}
}

type MsgRegisterWasmDependency struct {
	FromAddress           string                `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address" yaml:"from_address"`
	WasmDependencyMapping WasmDependencyMapping `protobuf:"bytes,2,opt,name=wasm_dependency_mapping,json=wasmDependencyMapping,proto3" json:"wasm_dependency_mapping" yaml:"wasm_dependency_mapping"`
}

func (m *MsgRegisterWasmDependency) Reset()         { *m = MsgRegisterWasmDependency{} }
func (m *MsgRegisterWasmDependency) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterWasmDependency) ProtoMessage()    {}
func (*MsgRegisterWasmDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9f3f1912ca0e01d, []int{1}
}
func (m *MsgRegisterWasmDependency) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterWasmDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterWasmDependency.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterWasmDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterWasmDependency.Merge(m, src)
}
func (m *MsgRegisterWasmDependency) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterWasmDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterWasmDependency.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterWasmDependency proto.InternalMessageInfo

func (m *MsgRegisterWasmDependency) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgRegisterWasmDependency) GetWasmDependencyMapping() WasmDependencyMapping {
	if m != nil {
		return m.WasmDependencyMapping
	}
	return WasmDependencyMapping{}
}

type MsgRegisterWasmDependencyResponse struct {
}

func (m *MsgRegisterWasmDependencyResponse) Reset()         { *m = MsgRegisterWasmDependencyResponse{} }
func (m *MsgRegisterWasmDependencyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterWasmDependencyResponse) ProtoMessage()    {}
func (*MsgRegisterWasmDependencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9f3f1912ca0e01d, []int{2}
}
func (m *MsgRegisterWasmDependencyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterWasmDependencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterWasmDependencyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterWasmDependencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterWasmDependencyResponse.Merge(m, src)
}
func (m *MsgRegisterWasmDependencyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterWasmDependencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterWasmDependencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterWasmDependencyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterWasmDependencyJSONFile)(nil), "cosmos.accesscontrol_x.v1beta1.RegisterWasmDependencyJSONFile")
	proto.RegisterType((*MsgRegisterWasmDependency)(nil), "cosmos.accesscontrol_x.v1beta1.MsgRegisterWasmDependency")
	proto.RegisterType((*MsgRegisterWasmDependencyResponse)(nil), "cosmos.accesscontrol_x.v1beta1.MsgRegisterWasmDependencyResponse")
}

func init() {
	proto.RegisterFile("cosmos/accesscontrol_x/v1beta1/tx.proto", fileDescriptor_a9f3f1912ca0e01d)
}

var fileDescriptor_a9f3f1912ca0e01d = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x52, 0x3d, 0x6f, 0xd4, 0x40,
	0x10, 0xf5, 0x06, 0x84, 0xc4, 0x86, 0xea, 0xf8, 0x3e, 0xa1, 0x35, 0x18, 0x89, 0x20, 0x04, 0x5e,
	0x72, 0x88, 0x82, 0x74, 0x39, 0x21, 0x8a, 0x93, 0x0e, 0x24, 0x53, 0x20, 0xd1, 0x58, 0x6b, 0x7b,
	0x58, 0x56, 0xd8, 0xbb, 0x8b, 0x67, 0x43, 0xe2, 0x1f, 0x40, 0x4f, 0x03, 0x25, 0xe2, 0x97, 0x50,
	0xa7, 0x4c, 0x49, 0x65, 0xa1, 0xbb, 0x06, 0x51, 0xe6, 0x17, 0xa0, 0xd8, 0x26, 0xe2, 0xa2, 0x38,
	0x27, 0xd1, 0xa4, 0xb2, 0x67, 0xe6, 0xbd, 0x7d, 0x6f, 0x9e, 0x86, 0xae, 0xa5, 0x06, 0x0b, 0x83,
	0x5c, 0xa4, 0x29, 0x20, 0xa6, 0x46, 0xbb, 0xd2, 0xe4, 0xf1, 0x0e, 0xff, 0xb0, 0x9e, 0x80, 0x13,
	0xeb, 0xdc, 0xed, 0x84, 0xb6, 0x34, 0xce, 0x0c, 0x58, 0x0b, 0x0c, 0x8f, 0x00, 0xc3, 0x0e, 0x38,
	0xbc, 0x24, 0x8d, 0x34, 0x0d, 0x94, 0x1f, 0xfc, 0xb5, 0xac, 0xe1, 0x0d, 0x69, 0x8c, 0xcc, 0x81,
	0x0b, 0xab, 0xb8, 0xd0, 0xda, 0x38, 0xe1, 0x94, 0xd1, 0xd8, 0x4d, 0xef, 0x75, 0xe2, 0x89, 0x40,
	0xe0, 0xef, 0xb7, 0xa0, 0xac, 0x0e, 0x75, 0xad, 0x90, 0x4a, 0x37, 0xe0, 0x0e, 0x3b, 0x5a, 0x62,
	0x74, 0xa1, 0xdf, 0x71, 0xee, 0x2f, 0xe1, 0x48, 0xd0, 0x80, 0xaa, 0x73, 0x13, 0x7c, 0x27, 0x94,
	0x45, 0x20, 0x15, 0x3a, 0x28, 0x5f, 0x09, 0x2c, 0x9e, 0x82, 0x05, 0x9d, 0x81, 0x4e, 0xab, 0xc9,
	0xcb, 0x17, 0xcf, 0x9f, 0xa9, 0x1c, 0x06, 0x9f, 0x09, 0xbd, 0xba, 0x2d, 0xb0, 0x88, 0xb3, 0xc3,
	0x59, 0x5c, 0x08, 0x6b, 0x95, 0x96, 0xd7, 0xc8, 0x4d, 0x72, 0x77, 0x75, 0xf4, 0x38, 0x3c, 0x39,
	0xa7, 0x70, 0xf1, 0xe5, 0x69, 0x4b, 0x1e, 0xdf, 0xd9, 0xad, 0x7d, 0x6f, 0xbf, 0xf6, 0x59, 0x25,
	0x8a, 0x7c, 0x23, 0xe8, 0xd1, 0x08, 0xa2, 0xcb, 0xdb, 0xc7, 0xd1, 0x37, 0xce, 0xfe, 0xfa, 0xe6,
	0x7b, 0xc1, 0xc7, 0x15, 0x7a, 0x7d, 0x8a, 0xf2, 0xf8, 0x1d, 0x06, 0x13, 0x7a, 0xe1, 0x4d, 0x69,
	0x8a, 0x58, 0x64, 0x59, 0x09, 0x88, 0x8d, 0xdf, 0xf3, 0xe3, 0xb5, 0xdf, 0xb5, 0xbf, 0xd0, 0xdf,
	0xaf, 0xfd, 0x8b, 0xad, 0x89, 0x7f, 0xbb, 0x41, 0xb4, 0x7a, 0x50, 0x6e, 0xb6, 0xd5, 0x89, 0x39,
	0xac, 0x9c, 0x7a, 0x0e, 0xb7, 0xe9, 0xad, 0xde, 0x18, 0x22, 0x40, 0x6b, 0x34, 0xc2, 0xe8, 0x2b,
	0xa1, 0x67, 0xa6, 0x28, 0x07, 0x5f, 0x08, 0xbd, 0xd2, 0x93, 0xd8, 0x93, 0x65, 0x3b, 0xf4, 0xaa,
	0x0c, 0x37, 0xff, 0x9b, 0xfa, 0xd7, 0xe0, 0x78, 0xb2, 0x3b, 0x63, 0x64, 0x6f, 0xc6, 0xc8, 0xcf,
	0x19, 0x23, 0x9f, 0xe6, 0xcc, 0xdb, 0x9b, 0x33, 0xef, 0xc7, 0x9c, 0x79, 0xaf, 0x1f, 0x4a, 0xe5,
	0xde, 0x6e, 0x25, 0x61, 0x6a, 0x0a, 0xde, 0x5d, 0x78, 0xfb, 0x79, 0x80, 0xd9, 0x3b, 0xee, 0x2a,
	0x0b, 0x47, 0x4e, 0x3e, 0x39, 0xd7, 0x5c, 0xf8, 0xa3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xde,
	0xb5, 0x47, 0x55, 0xee, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterWasmDependency(ctx context.Context, in *MsgRegisterWasmDependency, opts ...grpc.CallOption) (*MsgRegisterWasmDependencyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterWasmDependency(ctx context.Context, in *MsgRegisterWasmDependency, opts ...grpc.CallOption) (*MsgRegisterWasmDependencyResponse, error) {
	out := new(MsgRegisterWasmDependencyResponse)
	err := c.cc.Invoke(ctx, "/cosmos.accesscontrol_x.v1beta1.Msg/RegisterWasmDependency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterWasmDependency(context.Context, *MsgRegisterWasmDependency) (*MsgRegisterWasmDependencyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterWasmDependency(ctx context.Context, req *MsgRegisterWasmDependency) (*MsgRegisterWasmDependencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWasmDependency not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterWasmDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterWasmDependency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterWasmDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.accesscontrol_x.v1beta1.Msg/RegisterWasmDependency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterWasmDependency(ctx, req.(*MsgRegisterWasmDependency))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.accesscontrol_x.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWasmDependency",
			Handler:    _Msg_RegisterWasmDependency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/accesscontrol_x/v1beta1/tx.proto",
}

func (m *RegisterWasmDependencyJSONFile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterWasmDependencyJSONFile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterWasmDependencyJSONFile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WasmDependencyMapping.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgRegisterWasmDependency) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterWasmDependency) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterWasmDependency) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WasmDependencyMapping.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterWasmDependencyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterWasmDependencyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterWasmDependencyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RegisterWasmDependencyJSONFile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.WasmDependencyMapping.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterWasmDependency) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.WasmDependencyMapping.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterWasmDependencyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegisterWasmDependencyJSONFile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterWasmDependencyJSONFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterWasmDependencyJSONFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmDependencyMapping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterWasmDependency) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterWasmDependency: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterWasmDependency: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmDependencyMapping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterWasmDependencyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterWasmDependencyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterWasmDependencyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
