// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol_x/v1beta1/gov.proto

package types

import (
	fmt "fmt"
	accesscontrol "github.com/cosmos/cosmos-sdk/types/accesscontrol"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateResourceDependencyMappingProposal struct {
	Title                    string                                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description              string                                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	MessageDependencyMapping []accesscontrol.MessageDependencyMapping `protobuf:"bytes,3,rep,name=message_dependency_mapping,json=messageDependencyMapping,proto3" json:"message_dependency_mapping" yaml:"message_dependency_mapping"`
}

func (m *MsgUpdateResourceDependencyMappingProposal) Reset() {
	*m = MsgUpdateResourceDependencyMappingProposal{}
}
func (*MsgUpdateResourceDependencyMappingProposal) ProtoMessage() {}
func (*MsgUpdateResourceDependencyMappingProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_767c25f8ae5d2d80, []int{0}
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal.Merge(m, src)
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateResourceDependencyMappingProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateResourceDependencyMappingProposal proto.InternalMessageInfo

type MsgUpdateResourceDependencyMappingProposalJsonFile struct {
	Title                    string                                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description              string                                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	Deposit                  string                                   `protobuf:"bytes,3,opt,name=deposit,proto3" json:"deposit" yaml:"deposit"`
	MessageDependencyMapping []accesscontrol.MessageDependencyMapping `protobuf:"bytes,4,rep,name=message_dependency_mapping,json=messageDependencyMapping,proto3" json:"message_dependency_mapping" yaml:"message_dependency_mapping"`
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Reset() {
	*m = MsgUpdateResourceDependencyMappingProposalJsonFile{}
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) String() string {
	return proto.CompactTextString(m)
}
func (*MsgUpdateResourceDependencyMappingProposalJsonFile) ProtoMessage() {}
func (*MsgUpdateResourceDependencyMappingProposalJsonFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_767c25f8ae5d2d80, []int{1}
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile.Merge(m, src)
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalJsonFile proto.InternalMessageInfo

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) GetMessageDependencyMapping() []accesscontrol.MessageDependencyMapping {
	if m != nil {
		return m.MessageDependencyMapping
	}
	return nil
}

type MsgUpdateResourceDependencyMappingProposalResponse struct {
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) Reset() {
	*m = MsgUpdateResourceDependencyMappingProposalResponse{}
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgUpdateResourceDependencyMappingProposalResponse) ProtoMessage() {}
func (*MsgUpdateResourceDependencyMappingProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767c25f8ae5d2d80, []int{2}
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse.Merge(m, src)
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateResourceDependencyMappingProposalResponse proto.InternalMessageInfo

type MsgUpdateWasmDependencyMappingProposal struct {
	Title                 string                              `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description           string                              `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	ContractAddress       string                              `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address" yaml:"contract_address"`
	WasmDependencyMapping accesscontrol.WasmDependencyMapping `protobuf:"bytes,4,opt,name=wasm_dependency_mapping,json=wasmDependencyMapping,proto3" json:"wasm_dependency_mapping" yaml:"wasm_dependency_mapping"`
}

func (m *MsgUpdateWasmDependencyMappingProposal) Reset() {
	*m = MsgUpdateWasmDependencyMappingProposal{}
}
func (*MsgUpdateWasmDependencyMappingProposal) ProtoMessage() {}
func (*MsgUpdateWasmDependencyMappingProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_767c25f8ae5d2d80, []int{3}
}
func (m *MsgUpdateWasmDependencyMappingProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateWasmDependencyMappingProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateWasmDependencyMappingProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateWasmDependencyMappingProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateWasmDependencyMappingProposal.Merge(m, src)
}
func (m *MsgUpdateWasmDependencyMappingProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateWasmDependencyMappingProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateWasmDependencyMappingProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateWasmDependencyMappingProposal proto.InternalMessageInfo

type MsgUpdateWasmDependencyMappingProposalJsonFile struct {
	Title                 string                              `protobuf:"bytes,1,opt,name=title,proto3" json:"title" yaml:"title"`
	Description           string                              `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	Deposit               string                              `protobuf:"bytes,3,opt,name=deposit,proto3" json:"deposit" yaml:"deposit"`
	ContractAddress       string                              `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address" yaml:"contract_address"`
	WasmDependencyMapping accesscontrol.WasmDependencyMapping `protobuf:"bytes,5,opt,name=wasm_dependency_mapping,json=wasmDependencyMapping,proto3" json:"wasm_dependency_mapping" yaml:"wasm_dependency_mapping"`
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) Reset() {
	*m = MsgUpdateWasmDependencyMappingProposalJsonFile{}
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) String() string {
	return proto.CompactTextString(m)
}
func (*MsgUpdateWasmDependencyMappingProposalJsonFile) ProtoMessage() {}
func (*MsgUpdateWasmDependencyMappingProposalJsonFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_767c25f8ae5d2d80, []int{4}
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateWasmDependencyMappingProposalJsonFile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateWasmDependencyMappingProposalJsonFile.Merge(m, src)
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateWasmDependencyMappingProposalJsonFile.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateWasmDependencyMappingProposalJsonFile proto.InternalMessageInfo

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) GetWasmDependencyMapping() accesscontrol.WasmDependencyMapping {
	if m != nil {
		return m.WasmDependencyMapping
	}
	return accesscontrol.WasmDependencyMapping{}
}

func init() {
	proto.RegisterType((*MsgUpdateResourceDependencyMappingProposal)(nil), "cosmos.accesscontrol_x.v1beta1.MsgUpdateResourceDependencyMappingProposal")
	proto.RegisterType((*MsgUpdateResourceDependencyMappingProposalJsonFile)(nil), "cosmos.accesscontrol_x.v1beta1.MsgUpdateResourceDependencyMappingProposalJsonFile")
	proto.RegisterType((*MsgUpdateResourceDependencyMappingProposalResponse)(nil), "cosmos.accesscontrol_x.v1beta1.MsgUpdateResourceDependencyMappingProposalResponse")
	proto.RegisterType((*MsgUpdateWasmDependencyMappingProposal)(nil), "cosmos.accesscontrol_x.v1beta1.MsgUpdateWasmDependencyMappingProposal")
	proto.RegisterType((*MsgUpdateWasmDependencyMappingProposalJsonFile)(nil), "cosmos.accesscontrol_x.v1beta1.MsgUpdateWasmDependencyMappingProposalJsonFile")
}

func init() {
	proto.RegisterFile("cosmos/accesscontrol_x/v1beta1/gov.proto", fileDescriptor_767c25f8ae5d2d80)
}

var fileDescriptor_767c25f8ae5d2d80 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x4f, 0x8b, 0xd3, 0x40,
	0x1c, 0x4d, 0x36, 0xbb, 0x8a, 0x53, 0xd1, 0x25, 0x28, 0x5b, 0x0b, 0x66, 0xea, 0x80, 0x4b, 0x15,
	0x4d, 0xdc, 0xae, 0x28, 0xec, 0xcd, 0x22, 0x0a, 0x62, 0x41, 0x02, 0x22, 0xec, 0xa5, 0x4c, 0x93,
	0x21, 0x06, 0x9b, 0x4c, 0xc8, 0x6f, 0xf6, 0x4f, 0x6f, 0x1e, 0xf5, 0x26, 0x78, 0xf1, 0x66, 0x4f,
	0x7e, 0x96, 0x3d, 0xee, 0x45, 0x10, 0x91, 0x41, 0xda, 0x8b, 0xf4, 0xd8, 0x4f, 0x20, 0x66, 0x9a,
	0x52, 0xbb, 0xe9, 0xba, 0x5e, 0xac, 0x7b, 0x4a, 0xf2, 0xe6, 0xbd, 0x37, 0xbf, 0xbc, 0xc7, 0x30,
	0xa8, 0xe6, 0x71, 0x88, 0x38, 0x38, 0xd4, 0xf3, 0x18, 0x80, 0xc7, 0x63, 0x91, 0xf2, 0x4e, 0x6b,
	0xdf, 0xd9, 0xdd, 0x68, 0x33, 0x41, 0x37, 0x9c, 0x80, 0xef, 0xda, 0x49, 0xca, 0x05, 0x37, 0x2d,
	0xc5, 0xb4, 0x67, 0x98, 0xf6, 0x98, 0x59, 0xb9, 0x14, 0xf0, 0x80, 0x67, 0x54, 0xe7, 0xd7, 0x9b,
	0x52, 0x55, 0x6e, 0x15, 0xf9, 0x4f, 0xdc, 0x3d, 0x1e, 0x83, 0xa0, 0xb1, 0x80, 0x31, 0xfb, 0xce,
	0xb1, 0xec, 0xdf, 0x50, 0xa5, 0x20, 0x5f, 0x97, 0xd0, 0xcd, 0x26, 0x04, 0xcf, 0x13, 0x9f, 0x0a,
	0xe6, 0x32, 0xe0, 0x3b, 0xa9, 0xc7, 0x1e, 0xb2, 0x84, 0xc5, 0x3e, 0x8b, 0xbd, 0x6e, 0x93, 0x26,
	0x49, 0x18, 0x07, 0xcf, 0x52, 0x9e, 0x70, 0xa0, 0x1d, 0xd3, 0x41, 0x2b, 0x22, 0x14, 0x1d, 0x56,
	0xd6, 0xab, 0x7a, 0xed, 0x5c, 0xe3, 0xca, 0x50, 0x62, 0x05, 0x8c, 0x24, 0x3e, 0xdf, 0xa5, 0x51,
	0x67, 0x8b, 0x64, 0x9f, 0xc4, 0x55, 0xb0, 0xf9, 0x18, 0x95, 0x7c, 0x06, 0x5e, 0x1a, 0x26, 0x22,
	0xe4, 0x71, 0x79, 0x29, 0x93, 0x5d, 0x1f, 0x4a, 0x3c, 0x0d, 0x8f, 0x24, 0x36, 0x95, 0x78, 0x0a,
	0x24, 0xee, 0x34, 0xc5, 0xfc, 0xa8, 0xa3, 0x4a, 0xc4, 0x00, 0x68, 0xc0, 0x5a, 0xfe, 0x64, 0xbe,
	0x56, 0xa4, 0x06, 0x2c, 0x1b, 0x55, 0xa3, 0x56, 0xaa, 0xdf, 0xb3, 0x8b, 0x42, 0xce, 0x23, 0xb6,
	0x9b, 0x4a, 0x7f, 0xe4, 0xf7, 0x1a, 0x37, 0x0e, 0x24, 0xd6, 0x46, 0x12, 0x5f, 0x53, 0x53, 0xcc,
	0xdf, 0x87, 0xb8, 0xe5, 0x68, 0x8e, 0xc9, 0xd6, 0xea, 0x9b, 0x1e, 0xd6, 0x3e, 0xf4, 0xb0, 0xf6,
	0xa3, 0x87, 0xb5, 0xd7, 0xdf, 0xaa, 0x1a, 0x79, 0x6b, 0xa0, 0xfa, 0xc9, 0xc3, 0x7d, 0x02, 0x3c,
	0x7e, 0x14, 0x76, 0xd8, 0x02, 0x43, 0xbe, 0x8f, 0xce, 0xfa, 0x2c, 0xe1, 0x10, 0x8a, 0xb2, 0x91,
	0x99, 0x5c, 0x1d, 0x4a, 0x9c, 0x43, 0x23, 0x89, 0x2f, 0xe4, 0x06, 0x19, 0x40, 0xdc, 0x7c, 0xe9,
	0x4f, 0xed, 0x2c, 0x2f, 0xbc, 0x1d, 0x72, 0xf7, 0x6f, 0xaa, 0x70, 0x19, 0x24, 0x3c, 0x06, 0x46,
	0x3e, 0x19, 0x68, 0x7d, 0x22, 0x7b, 0x41, 0x21, 0xfa, 0x1f, 0x8f, 0xc6, 0x36, 0x5a, 0xcd, 0xb2,
	0xa4, 0x9e, 0x68, 0x51, 0xdf, 0x4f, 0x19, 0xc0, 0xb8, 0x3e, 0x67, 0x28, 0xf1, 0x91, 0xb5, 0x91,
	0xc4, 0x6b, 0xca, 0x72, 0x76, 0x85, 0xb8, 0x17, 0x73, 0xe8, 0x81, 0x42, 0xcc, 0xf7, 0x3a, 0x5a,
	0xdb, 0xa3, 0x10, 0x15, 0xb7, 0xaa, 0xd7, 0x4a, 0xf5, 0xcd, 0xe3, 0x5b, 0x2d, 0x0c, 0xad, 0xb1,
	0x3e, 0xae, 0xd4, 0x52, 0x83, 0xcc, 0xd9, 0x81, 0xb8, 0x97, 0xf7, 0x8a, 0xe4, 0x05, 0x47, 0xed,
	0xb3, 0x81, 0xec, 0x93, 0x15, 0x75, 0x9a, 0x8f, 0x59, 0x51, 0xd3, 0xcb, 0xff, 0xa0, 0xe9, 0x95,
	0x45, 0x35, 0xdd, 0x78, 0x7a, 0xd0, 0xb7, 0xf4, 0xc3, 0xbe, 0xa5, 0x7f, 0xef, 0x5b, 0xfa, 0xbb,
	0x81, 0xa5, 0x1d, 0x0e, 0x2c, 0xed, 0xcb, 0xc0, 0xd2, 0xb6, 0xeb, 0x41, 0x28, 0x5e, 0xee, 0xb4,
	0x6d, 0x8f, 0x47, 0xce, 0xf8, 0xda, 0x53, 0x8f, 0xdb, 0xe0, 0xbf, 0x72, 0xf6, 0x67, 0xee, 0x40,
	0xd1, 0x4d, 0x18, 0xb4, 0xcf, 0x64, 0x97, 0xde, 0xe6, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc,
	0x4a, 0xd7, 0x60, 0xb6, 0x07, 0x00, 0x00,
}

func (m *MsgUpdateResourceDependencyMappingProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateResourceDependencyMappingProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateResourceDependencyMappingProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageDependencyMapping) > 0 {
		for iNdEx := len(m.MessageDependencyMapping) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageDependencyMapping[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGov(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageDependencyMapping) > 0 {
		for iNdEx := len(m.MessageDependencyMapping) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageDependencyMapping[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGov(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Deposit) > 0 {
		i -= len(m.Deposit)
		copy(dAtA[i:], m.Deposit)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Deposit)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateWasmDependencyMappingProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateWasmDependencyMappingProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateWasmDependencyMappingProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WasmDependencyMapping.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGov(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintGov(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WasmDependencyMapping.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGov(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintGov(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Deposit) > 0 {
		i -= len(m.Deposit)
		copy(dAtA[i:], m.Deposit)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Deposit)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGov(dAtA []byte, offset int, v uint64) int {
	offset -= sovGov(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateResourceDependencyMappingProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	if len(m.MessageDependencyMapping) > 0 {
		for _, e := range m.MessageDependencyMapping {
			l = e.Size()
			n += 1 + l + sovGov(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Deposit)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	if len(m.MessageDependencyMapping) > 0 {
		for _, e := range m.MessageDependencyMapping {
			l = e.Size()
			n += 1 + l + sovGov(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateResourceDependencyMappingProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateWasmDependencyMappingProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = m.WasmDependencyMapping.Size()
	n += 1 + l + sovGov(uint64(l))
	return n
}

func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Deposit)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = m.WasmDependencyMapping.Size()
	n += 1 + l + sovGov(uint64(l))
	return n
}

func sovGov(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGov(x uint64) (n int) {
	return sovGov(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateResourceDependencyMappingProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageDependencyMapping = append(m.MessageDependencyMapping, accesscontrol.MessageDependencyMapping{})
			if err := m.MessageDependencyMapping[len(m.MessageDependencyMapping)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateResourceDependencyMappingProposalJsonFile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalJsonFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalJsonFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageDependencyMapping = append(m.MessageDependencyMapping, accesscontrol.MessageDependencyMapping{})
			if err := m.MessageDependencyMapping[len(m.MessageDependencyMapping)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateResourceDependencyMappingProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateResourceDependencyMappingProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateWasmDependencyMappingProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateWasmDependencyMappingProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateWasmDependencyMappingProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmDependencyMapping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateWasmDependencyMappingProposalJsonFile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateWasmDependencyMappingProposalJsonFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateWasmDependencyMappingProposalJsonFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmDependencyMapping.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGov(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGov
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGov
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGov
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGov
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGov        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGov          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGov = fmt.Errorf("proto: unexpected end of group")
)
