// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/params/v1beta1/types.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines fee params that are controlled through governance
type FeesParams struct {
	GlobalMinimumGasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=global_minimum_gas_prices,json=globalMinimumGasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"global_minimum_gas_prices"`
	AllowedFeeDenoms       []string                                    `protobuf:"bytes,2,rep,name=allowed_fee_denoms,json=allowedFeeDenoms,proto3" json:"allowed_fee_denoms,omitempty"`
}

func (m *FeesParams) Reset()         { *m = FeesParams{} }
func (m *FeesParams) String() string { return proto.CompactTextString(m) }
func (*FeesParams) ProtoMessage()    {}
func (*FeesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aff575ac42419531, []int{0}
}
func (m *FeesParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeesParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesParams.Merge(m, src)
}
func (m *FeesParams) XXX_Size() int {
	return m.Size()
}
func (m *FeesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesParams.DiscardUnknown(m)
}

var xxx_messageInfo_FeesParams proto.InternalMessageInfo

func (m *FeesParams) GetGlobalMinimumGasPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.GlobalMinimumGasPrices
	}
	return nil
}

func (m *FeesParams) GetAllowedFeeDenoms() []string {
	if m != nil {
		return m.AllowedFeeDenoms
	}
	return nil
}

type CosmosGasParams struct {
	CosmosGasMultiplierNumerator   uint64 `protobuf:"varint,1,opt,name=cosmos_gas_multiplier_numerator,json=cosmosGasMultiplierNumerator,proto3" json:"cosmos_gas_multiplier_numerator,omitempty"`
	CosmosGasMultiplierDenominator uint64 `protobuf:"varint,2,opt,name=cosmos_gas_multiplier_denominator,json=cosmosGasMultiplierDenominator,proto3" json:"cosmos_gas_multiplier_denominator,omitempty"`
}

func (m *CosmosGasParams) Reset()         { *m = CosmosGasParams{} }
func (m *CosmosGasParams) String() string { return proto.CompactTextString(m) }
func (*CosmosGasParams) ProtoMessage()    {}
func (*CosmosGasParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aff575ac42419531, []int{1}
}
func (m *CosmosGasParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CosmosGasParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CosmosGasParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CosmosGasParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CosmosGasParams.Merge(m, src)
}
func (m *CosmosGasParams) XXX_Size() int {
	return m.Size()
}
func (m *CosmosGasParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CosmosGasParams.DiscardUnknown(m)
}

var xxx_messageInfo_CosmosGasParams proto.InternalMessageInfo

func (m *CosmosGasParams) GetCosmosGasMultiplierNumerator() uint64 {
	if m != nil {
		return m.CosmosGasMultiplierNumerator
	}
	return 0
}

func (m *CosmosGasParams) GetCosmosGasMultiplierDenominator() uint64 {
	if m != nil {
		return m.CosmosGasMultiplierDenominator
	}
	return 0
}

type GenesisState struct {
	FeesParams      FeesParams      `protobuf:"bytes,1,opt,name=fees_params,json=feesParams,proto3" json:"fees_params"`
	CosmosGasParams CosmosGasParams `protobuf:"bytes,2,opt,name=cosmos_gas_params,json=cosmosGasParams,proto3" json:"cosmos_gas_params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_aff575ac42419531, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetFeesParams() FeesParams {
	if m != nil {
		return m.FeesParams
	}
	return FeesParams{}
}

func (m *GenesisState) GetCosmosGasParams() CosmosGasParams {
	if m != nil {
		return m.CosmosGasParams
	}
	return CosmosGasParams{}
}

func init() {
	proto.RegisterType((*FeesParams)(nil), "cosmos.params.v1beta1.FeesParams")
	proto.RegisterType((*CosmosGasParams)(nil), "cosmos.params.v1beta1.CosmosGasParams")
	proto.RegisterType((*GenesisState)(nil), "cosmos.params.v1beta1.GenesisState")
}

func init() { proto.RegisterFile("cosmos/params/v1beta1/types.proto", fileDescriptor_aff575ac42419531) }

var fileDescriptor_aff575ac42419531 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xe3, 0x6e, 0x42, 0xc2, 0x45, 0x1a, 0x44, 0x80, 0xca, 0x34, 0xb9, 0x5d, 0x0f, 0xa8,
	0x12, 0xe0, 0x68, 0xdb, 0x37, 0xd8, 0xca, 0xc6, 0x0e, 0x45, 0x55, 0xb8, 0x20, 0x2e, 0x91, 0x93,
	0xbe, 0x0d, 0x16, 0x71, 0x1c, 0xc5, 0x0e, 0x7f, 0xbe, 0x03, 0x07, 0xbe, 0x03, 0x17, 0xc4, 0x91,
	0x4f, 0x51, 0x6e, 0x3d, 0x72, 0x02, 0x94, 0x7e, 0x11, 0x14, 0xdb, 0x69, 0x51, 0x55, 0x38, 0x25,
	0xb2, 0x1f, 0xff, 0x9e, 0xe7, 0xf5, 0x63, 0x7c, 0x9c, 0x48, 0x25, 0xa4, 0x0a, 0x0a, 0x56, 0x32,
	0xa1, 0x82, 0xb7, 0x27, 0x31, 0x68, 0x76, 0x12, 0xe8, 0x0f, 0x05, 0x28, 0x5a, 0x94, 0x52, 0x4b,
	0xff, 0x9e, 0x95, 0x50, 0x2b, 0xa1, 0x4e, 0x72, 0x78, 0x37, 0x95, 0xa9, 0x34, 0x8a, 0xa0, 0xf9,
	0xb3, 0xe2, 0x43, 0xe2, 0x78, 0x31, 0x53, 0xb0, 0xa6, 0x25, 0x92, 0xe7, 0x76, 0x7f, 0xf8, 0x1d,
	0x61, 0x7c, 0x09, 0xa0, 0xa6, 0x06, 0xe6, 0x7f, 0x44, 0xf8, 0x41, 0x9a, 0xc9, 0x98, 0x65, 0x91,
	0xe0, 0x39, 0x17, 0x95, 0x88, 0x52, 0xa6, 0xa2, 0xa2, 0xe4, 0x09, 0xa8, 0x1e, 0x1a, 0xec, 0x8d,
	0xba, 0xa7, 0x47, 0xd4, 0x05, 0x68, 0x98, 0xad, 0x3d, 0x1d, 0x43, 0x72, 0x21, 0x79, 0x7e, 0x7e,
	0xb6, 0xf8, 0xd9, 0xf7, 0xbe, 0xfe, 0xea, 0x3f, 0x4a, 0xb9, 0x7e, 0x5d, 0xc5, 0x34, 0x91, 0x22,
	0x70, 0x19, 0xec, 0xe7, 0x89, 0x9a, 0xbd, 0x71, 0xf3, 0xb8, 0x33, 0x2a, 0xbc, 0x6f, 0x3d, 0x27,
	0xd6, 0xf2, 0x8a, 0xa9, 0xa9, 0x31, 0xf4, 0x1f, 0x63, 0x9f, 0x65, 0x99, 0x7c, 0x07, 0xb3, 0x68,
	0x0e, 0x10, 0xcd, 0x20, 0x97, 0x42, 0xf5, 0x3a, 0x83, 0xbd, 0xd1, 0xcd, 0xf0, 0xb6, 0xdb, 0xb9,
	0x04, 0x18, 0x9b, 0xf5, 0xe1, 0x67, 0x84, 0x0f, 0x2e, 0x8c, 0x47, 0x43, 0xb0, 0x03, 0x3d, 0xc5,
	0x7d, 0x6b, 0x6b, 0xe6, 0x10, 0x55, 0xa6, 0x79, 0x91, 0x71, 0x28, 0xa3, 0xbc, 0x12, 0x50, 0x32,
	0x2d, 0xcb, 0x1e, 0x1a, 0xa0, 0xd1, 0x7e, 0x78, 0x94, 0xb4, 0x27, 0x27, 0x6b, 0xd1, 0xf3, 0x56,
	0xe3, 0x5f, 0xb7, 0xc5, 0x6c, 0x63, 0x4c, 0x24, 0x9e, 0x1b, 0x50, 0xc7, 0x80, 0xc8, 0x0e, 0xd0,
	0x78, 0xa3, 0x1a, 0x7e, 0x43, 0xf8, 0xd6, 0x15, 0xe4, 0xa0, 0xb8, 0x7a, 0xa1, 0x99, 0x06, 0xff,
	0x19, 0xee, 0xce, 0x01, 0x54, 0x64, 0xfb, 0x34, 0x71, 0xba, 0xa7, 0xc7, 0x74, 0x67, 0xcb, 0x74,
	0xd3, 0xd5, 0xf9, 0x7e, 0x73, 0xd3, 0x21, 0x9e, 0x6f, 0xda, 0x7b, 0x89, 0xef, 0xfc, 0x95, 0xd2,
	0xf1, 0x3a, 0x86, 0xf7, 0xf0, 0x1f, 0xbc, 0xad, 0xfb, 0x72, 0xd0, 0x83, 0x64, 0x6b, 0xf9, 0xfa,
	0x4b, 0x4d, 0xd0, 0xa2, 0x26, 0x68, 0x59, 0x13, 0xf4, 0xbb, 0x26, 0xe8, 0xd3, 0x8a, 0x78, 0xcb,
	0x15, 0xf1, 0x7e, 0xac, 0x88, 0xf7, 0xea, 0xff, 0x5d, 0xbf, 0x6f, 0x1f, 0xb3, 0x29, 0x3d, 0xbe,
	0x61, 0x1e, 0xde, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x83, 0x6a, 0x5c, 0xea, 0x02,
	0x00, 0x00,
}

func (this *FeesParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeesParams)
	if !ok {
		that2, ok := that.(FeesParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.GlobalMinimumGasPrices) != len(that1.GlobalMinimumGasPrices) {
		return false
	}
	for i := range this.GlobalMinimumGasPrices {
		if !this.GlobalMinimumGasPrices[i].Equal(&that1.GlobalMinimumGasPrices[i]) {
			return false
		}
	}
	if len(this.AllowedFeeDenoms) != len(that1.AllowedFeeDenoms) {
		return false
	}
	for i := range this.AllowedFeeDenoms {
		if this.AllowedFeeDenoms[i] != that1.AllowedFeeDenoms[i] {
			return false
		}
	}
	return true
}
func (this *CosmosGasParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CosmosGasParams)
	if !ok {
		that2, ok := that.(CosmosGasParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CosmosGasMultiplierNumerator != that1.CosmosGasMultiplierNumerator {
		return false
	}
	if this.CosmosGasMultiplierDenominator != that1.CosmosGasMultiplierDenominator {
		return false
	}
	return true
}
func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.FeesParams.Equal(&that1.FeesParams) {
		return false
	}
	if !this.CosmosGasParams.Equal(&that1.CosmosGasParams) {
		return false
	}
	return true
}
func (m *FeesParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeesParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeesParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedFeeDenoms) > 0 {
		for iNdEx := len(m.AllowedFeeDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedFeeDenoms[iNdEx])
			copy(dAtA[i:], m.AllowedFeeDenoms[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.AllowedFeeDenoms[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.GlobalMinimumGasPrices) > 0 {
		for iNdEx := len(m.GlobalMinimumGasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GlobalMinimumGasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CosmosGasParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CosmosGasParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CosmosGasParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CosmosGasMultiplierDenominator != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CosmosGasMultiplierDenominator))
		i--
		dAtA[i] = 0x10
	}
	if m.CosmosGasMultiplierNumerator != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CosmosGasMultiplierNumerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CosmosGasParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.FeesParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeesParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GlobalMinimumGasPrices) > 0 {
		for _, e := range m.GlobalMinimumGasPrices {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.AllowedFeeDenoms) > 0 {
		for _, s := range m.AllowedFeeDenoms {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *CosmosGasParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CosmosGasMultiplierNumerator != 0 {
		n += 1 + sovTypes(uint64(m.CosmosGasMultiplierNumerator))
	}
	if m.CosmosGasMultiplierDenominator != 0 {
		n += 1 + sovTypes(uint64(m.CosmosGasMultiplierDenominator))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FeesParams.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.CosmosGasParams.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeesParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeesParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeesParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalMinimumGasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GlobalMinimumGasPrices = append(m.GlobalMinimumGasPrices, types.DecCoin{})
			if err := m.GlobalMinimumGasPrices[len(m.GlobalMinimumGasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedFeeDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedFeeDenoms = append(m.AllowedFeeDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CosmosGasParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CosmosGasParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CosmosGasParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosGasMultiplierNumerator", wireType)
			}
			m.CosmosGasMultiplierNumerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CosmosGasMultiplierNumerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosGasMultiplierDenominator", wireType)
			}
			m.CosmosGasMultiplierDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CosmosGasMultiplierDenominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeesParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeesParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosGasParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CosmosGasParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
